# Визуализация результата

In [78]:
import json
import pandas as pd

with open(
    "../data/laughter_segmentation/Разгоны [тизер].json", "r", encoding="utf-8"
) as f:
    data = json.load(f)  # data = {"3.6": 0.66, "3.8": 0.69, ...}

df = pd.DataFrame(list(data.items()), columns=["time", "confidence"], dtype=float)
df

       time  confidence
0       3.6        0.66
1       3.8        0.69
2       3.9        0.64
3       5.1        0.63
4       5.2        0.51
...     ...         ...
1714  785.5        0.84
1715  785.6        0.84
1716  785.7        0.90
1717  785.8        0.79
1718  786.1        0.57

[1719 rows x 2 columns]

In [67]:
df["time"] = df["time"].round(0)

In [77]:
df = df.groupby("time").agg("mean")

df

       confidence
time
4.0      0.663333
5.0      0.645000
6.0      0.632500
26.0     0.805000
27.0     0.833333
...           ...
782.0    0.863333
783.0    0.926667
784.0    0.903636
785.0    0.750000
786.0    0.788000

[286 rows x 1 columns]