# Анализ тем

In [ ]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

topics = [
    "Алкоголь, наркотики и зависимость",
    "Финансы",
    "Животные и домашние питомцы",
    "Здоровье и медицина",
    "Интернет и технологии",
    "Истории и байки",
    "Кино и музыка",
    "Национальности и стереотипы",
    "Отношения",
    "Политика и общество",
    "Преступность, тюрьма и правосудие",
    "Психотерапия",
    "Работа и учеба",
    "Секс и половые связи",
    "Семья, дети и родственники",
    "Спорт",
    "Смерть",
    "Философия и смысл жизни",
    "Эмиграция, переезд",
    "Мода и внешний вид",
]

model = SentenceTransformer(
    "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
)
embeddings = model.encode(topics)

# Расчет косинусного сходства
similarity_matrix = cosine_similarity(embeddings)

# Визуализация матрицы сходства
plt.figure(figsize=(12, 10))
sns.heatmap(
    similarity_matrix,
    xticklabels=topics,
    yticklabels=topics,
    cmap="coolwarm",
    annot=False,
)
plt.title("Косинусная близость между темами")
plt.xticks(rotation=90)
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

# TEST

### Получение метаданных плейлиста

In [1]:
import youtube_downloader

playlist_info = youtube_downloader.yt_playlist_extract_info(
    "https://www.youtube.com/watch?v=MaVc3dqiEI4&list=PLcQngyvNgfmLi9eyV9reNMqu-pbdKErKr"
)

### Загрузка метаданных плейлиста в Postgres

In [9]:
import re


def normalize_title(title: str) -> str:
    # Заменяем всё, что не буква или цифра, на подчёркивание
    temp = re.sub(r"[^\w\dа-яА-ЯёЁ]+", "_", title)
    # Удаляем повторяющиеся подчёркивания
    temp = re.sub(r"__+", "_", temp)
    # Удаляем подчёркивания в начале и в конце
    return temp.strip("_")


# Пример
s = "Вечер Судного Дня. ___1!!Дело： еда против комфорта"
print(normalize_title(s))

Вечер_Судного_Дня_1_Дело_еда_против_комфорта

In [4]:
import youtube_downloader as yd
import config
import yt_dlp

video_url = "https://www.youtube.com/watch?v=duXr-dUXtw4"

with yt_dlp.YoutubeDL(config.YDL_OPTS) as ydl:
    # 1. Получаем информацию о видео, не скачивая его
    info_dict = ydl.extract_info(video_url, download=False)

    # 2. Определяем ожидаемый путь к файлу
    filename = ydl.prepare_filename(info_dict)
    # audio_path = Path(filename).with_suffix(".m4a")

    # # 3. Проверяем, существует ли файл
    # if audio_path.exists():
    #     logging.info(f"Файл скачан ранее: {audio_path}")
    #     return audio_path

    # # 4. Если файла нет, запускаем полное скачивание и обработку
    # ydl.extract_info(video_url, download=True)

    # logging.info("Скачивание аудио завершено")

filename

'/Users/aleksandr/Documents/Projects/StandUP_project/data/audio/Вечер Судного Дня. Дело： еда против комфорта.m4a'

In [11]:
import psycopg

# Параметры подключения (замените на свои)
conn_params = {
    "dbname": "standup",
    "user": "standup",
    "password": "standup",
    "host": "postgresql.standup.orb.local",
    "port": "5432",
}

try:
    # Подключение к БД
    conn = psycopg.connect(**conn_params)
    cur = conn.cursor()

    # SQL-запрос для вставки
    insert_query = """
    INSERT INTO standup_raw.process_video (
        channel_id, channel_name, playlist_id, playlist_title, video_id, video_title, 
        viedeo_url, duration, view_count, comment_count, like_count, upload_date, 
        transcribe_json, llm_chapter_json, SoundFileClassifier_app
    ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    """

    # Подготовка данных: список кортежей из значений словарей
    data = [
        (
            item["channel_id"],
            item["channel_name"],
            item["playlist_id"],
            item["playlist_title"],
            item["video_id"],
            item["video_title"],
            item["viedeo_url"],
            item["duration"],
            item["view_count"],
            item["comment_count"],
            item["like_count"],
            item["upload_date"],
            item["transcribe_json"],
            item["llm_chapter_json"],
            item["SoundFileClassifier_app"],
        )
        for item in playlist_info
    ]

    # Выполнение множественной вставки
    cur.executemany(insert_query, data)

    # Коммит изменений
    conn.commit()
    print(f"Успешно вставлено {len(playlist_info)} записей.")

except (Exception, psycopg.Error) as error:
    print(f"Ошибка: {error}")
finally:
    if cur:
        cur.close()
    if conn:
        conn.close()

Успешно вставлено 5 записей.

### Наладка цикла загрузки всех данных через функции и загрузка в Postgres

## Итерация по метаданным и запись в json ответы

In [1]:
import time
from io import StringIO
import pandas as pd
from google import genai
from google.genai import types
import config
import requests
import re
import json
import yt_dlp

TIME_RE = re.compile(
    r"(\d{2}):(\d{2}):(\d{2}),(\d{3})\s*-->\s*(\d{2}):(\d{2}):(\d{2}),(\d{3})"
)


def yt_extract_info(video_url):
    with yt_dlp.YoutubeDL(config.YDL_OPTS) as ydl:
        info_dict = ydl.extract_info(video_url, download=False)
        return info_dict


def to_seconds_int(h, m, s, ms):
    """
    Переводит компоненты таймкода в секунды,
    округляя до целого числа.
    """
    total = int(h) * 3600 + int(m) * 60 + int(s) + int(ms) / 1000
    return int(round(total))


def format_srt(raw_srt: str, as_json: bool = False):
    lines = raw_srt.splitlines()
    items = []
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        if re.fullmatch(r"\d+", line):
            i += 1
            continue
        m = TIME_RE.match(line)
        if not m:
            i += 1
            continue
        start = to_seconds_int(*m.groups()[:4])
        end = to_seconds_int(*m.groups()[4:])
        i += 1
        txt_lines = []
        while i < len(lines) and lines[i].strip():
            txt_lines.append(lines[i].strip())
            i += 1
        txt = " ".join(txt_lines)
        txt = re.sub(r"\[|\]|>>", "", txt).strip().lower()
        items.append((start, end, txt))

    if as_json:
        return json.dumps(
            [{"start": s, "end": e, "text": t} for s, e, t in items],
            ensure_ascii=False,
            indent=2,
        )
    else:
        # Только стартовый таймкод и текст
        return "\n".join(f"{s} {t}" for s, _, t in items)


df_full = pd.read_json("../data/test/df_full.json")
df_full = df_full.iloc[140:141]

for index, row in df_full.iterrows():
    try:
        title = row["title"]
        url = row["original_url"]
        duration = row["duration"]

        info_dict = yt_extract_info(url)
        captions = info_dict.get("automatic_captions", {}).get("ru", [])
        srt_entry = next((item for item in captions if item.get("ext") == "srt"), None)
        srt_url = srt_entry["url"]

        # !!! ошибка 'NoneType' object is not subscriptable - обработать ошибку отсутствия сабов !!! нужно будет использовать транскрибацию
        response = requests.get(srt_url)

        if response.status_code == 200:
            srt_text = response.text
        else:
            raise Exception(f"Ошибка загрузки: {response.status_code}")

        tsv_content = format_srt(srt_text, as_json=False)

        client = genai.Client(
            api_key=config.GEMINI_API_KEY,
        )

        model = "gemini-2.5-flash"

        promt = f"""
        **Роль:** Ты — продвинутый ИИ-аналитик, эксперт в тематическом анализе юмористических шоу и стендапов.
        **Задача:** Проанализировать предоставленный транскрипт выступления и выделить основные смысловые темы, указав их таймкоды.

        ВАЖНАЯ ИНФОРМАЦИЯ:
        Общая длительность выступления: {duration} секунд.

        # Правила Анализа
        1.  **Крупные блоки:** Выделяй только крупные, ключевые темы. Тема — это смысловой блок, обсуждаемый несколько минут (например, "отношения с родителями", "опыт жизни за границей", "неловкие ситуации"). Не дроби выступление на отдельные шутки.
        2.  **Строгая хронология:** Темы должны идти в том же порядке, в котором они появляются. Массив `timestamp` должен быть строго отсортирован по возрастанию.
        3.  **Рекламные интеграции:** Обязательно распознавай рекламные блоки. Для них используй строго только название темы (theme) "Реклама".
        4.  **Контроль длительности:** Последний таймкод НЕ ДОЛЖЕН превышать общую длительность выступления ({duration} секунд).
        5.  **Контроль пропорций:** Ни одна тема не должна занимать более трети от общего времени выступления.
        """

        generate_content_config = types.GenerateContentConfig(
            temperature=0,
            thinking_config=types.ThinkingConfig(
                thinking_budget=-1,
            ),
            response_mime_type="application/json",
            response_schema=genai.types.Schema(
                type=genai.types.Type.OBJECT,
                required=["theme", "timestamp"],
                properties={
                    "theme": genai.types.Schema(
                        type=genai.types.Type.ARRAY,
                        items=genai.types.Schema(
                            type=genai.types.Type.STRING,
                        ),
                    ),
                    "timestamp": genai.types.Schema(
                        type=genai.types.Type.ARRAY,
                        items=genai.types.Schema(
                            type=genai.types.Type.INTEGER,
                        ),
                    ),
                },
            ),
            system_instruction=[
                types.Part.from_text(text=promt),
            ],
        )

        response = client.models.generate_content(
            model=model,
            contents=types.Content(
                parts=[
                    types.Part(text=tsv_content),
                ]
            ),
            config=generate_content_config,
        )
        # Сохранение результата
        # !!! All arrays must be of the same length !!! обработать ошибку некорректной выдачи от LLM, списки разной длины и фейлится созранение
        df_chunk = pd.read_json(StringIO(response.text))
        out_path = f"../data/test/time_text/{title}.json"
        df_chunk.to_json(out_path, force_ascii=False, indent=2)
        print(title, " - обработано")
    except Exception as e:
        print(title, f" - ошибка {e}")
    time.sleep(10)

Разгоны #18 [Александр Киселёв, Дима Гаврилов, Давид Квахаджелидзе, Коля Андреев,  Эльдар Гусейнов]  - ошибка Ошибка загрузки: 429

KeyboardInterrupt:

In [4]:
import pandas as pd

df_full = pd.read_json("../data/test/df_full.json")
df_full = df_full.iloc[140:]
df_full

,id,title,duration,view_count,comment_count,like_count,upload_date,chapters,original_url
140,2NzW8EkZ9Hc,"Разгоны #18 [Александр Киселёв, Дима Гаврилов,...",3472,1342493,1000,30869,20200828,None,https://www.youtube.com/watch?v=2NzW8EkZ9Hc
141,ivmQ3tM12dY,"Разгоны #17 [Идрак Мирзализаде, Эльдар Гусейно...",3915,2105354,1200,43248,20200814,None,https://www.youtube.com/watch?v=ivmQ3tM12dY
142,TVtakPe6kL4,"Разгоны #16 [новогодние праздники, откровения ...",2380,1050760,978,37966,20200620,None,https://www.youtube.com/watch?v=TVtakPe6kL4
143,rWv9HTi6Kh4,"Разгоны #15 [эволюция, пердёж, суперклей]",3133,1517821,989,35105,20200503,None,https://www.youtube.com/watch?v=rWv9HTi6Kh4
144,uvZ2vKQUgZ4,Разгоны #14 [Анна Карёнина/ ремонт/ красота по...,1793,998212,604,26169,20200320,None,https://www.youtube.com/watch?v=uvZ2vKQUgZ4
145,xw0mX3XTVWg,Разгоны #13 [продуктовые/ гляделки/ криокамеры],1581,1260336,1000,34445,20200124,None,https://www.youtube.com/watch?v=xw0mX3XTVWg
146,0Tbvlh5a6Wc,Разгоны #12 [бандана/ халва/ чучела],3228,1857701,1300,40898,20191220,None,https://www.youtube.com/watch?v=0Tbvlh5a6Wc
147,u0Ury_yZW5M,Разгоны #11 [акинатор/ утро с девушкой/ цитаты...,2715,1323987,813,29780,20191113,None,https://www.youtube.com/watch?v=u0Ury_yZW5M
148,xfLIlmM59MA,Разгоны #10 [шарики/лунатизм/имена],3890,3639855,2000,61745,20191005,None,https://www.youtube.com/watch?v=xfLIlmM59MA
149,-V-o5m6rIcw,Разгоны #9 [коты/роботы/самолеты],2833,1545736,1300,38593,20190915,None,https://www.youtube.com/watch?v=-V-o5m6rIcw
150,1phcDii1rBY,Разгоны #8 [тропинка/ интимные зоны/ митинги],2759,2226451,1500,57946,20190803,None,https://www.youtube.com/watch?v=1phcDii1rBY
151,EnIzWwF77tI,Разгоны #7 [попугай/ плацкарт/ официанты],1939,1294224,483,32376,20190729,None,https://www.youtube.com/watch?v=EnIzWwF77tI
152,8F4HG_87of0,Разгоны #6 [кофе/ полиция/ знакомства ],2806,2379717,1300,51821,20190704,None,https://www.youtube.com/watch?v=8F4HG_87of0
153,mHKDdaP_vA0,Разгоны #5 [сумка с деньгами/ крещение/ видеои...,1586,1116229,578,29731,20190611,None,https://www.youtube.com/watch?v=mHKDdaP_vA0
154,2xeSuRx1vnU,Разгоны #4 [айклауд/ шпионы/ необычные презерв...,1525,1257410,536,29468,20190517,None,https://www.youtube.com/watch?v=2xeSuRx1vnU
155,gvtUzd2PcDk,Разгоны #3 [троянский конь/ пластические опера...,2072,1397363,627,31810,20190331,None,https://www.youtube.com/watch?v=gvtUzd2PcDk
156,NqU_O94qEg8,Разгоны #2 [документы/ родители/ животные],1916,1380952,800,33625,20190314,None,https://www.youtube.com/watch?v=NqU_O94qEg8
157,REdAajgSYvg,Разгоны [тизер],787,548666,438,18758,20190202,None,https://www.youtube.com/watch?v=REdAajgSYvg

# Наладка отдельных функций

## Наладка транскрибации

In [ ]:
import transcribe

result = transcribe.transcribe_audio(
    "../data/audio/Вася Медведев - Встреча с богами [Шоу Историй].m4a"
)

'{\n  "id":{\n    "0":0,\n    "1":1,\n    "2":2,\n    "3":3,\n    "4":4,\n    "5":5,\n    "6":6,\n    "7":7,\n    "8":8,\n    "9":9,\n    "10":10,\n    "11":11,\n    "12":12,\n    "13":13,\n    "14":14,\n    "15":15,\n    "16":16,\n    "17":17,\n    "18":18,\n    "19":19,\n    "20":20,\n    "21":21,\n    "22":22,\n    "23":23,\n    "24":24,\n    "25":25,\n    "26":26,\n    "27":27,\n    "28":28,\n    "29":29,\n    "30":30,\n    "31":31,\n    "32":32,\n    "33":33,\n    "34":34,\n    "35":35,\n    "36":36,\n    "37":37,\n    "38":38,\n    "39":39,\n    "40":40,\n    "41":41,\n    "42":42,\n    "43":44,\n    "44":45,\n    "45":46,\n    "46":47,\n    "47":48,\n    "48":49,\n    "49":50,\n    "50":51,\n    "51":52,\n    "52":53,\n    "53":54,\n    "54":55,\n    "55":56,\n    "56":57,\n    "57":58,\n    "58":59,\n    "59":60,\n    "60":61,\n    "61":62,\n    "62":63,\n    "63":64,\n    "64":65,\n    "65":66,\n    "66":67,\n    "67":68,\n    "68":69,\n    "69":70,\n    "70":71,\n    "71":72,\n    "72":73,\n    "73":74,\n    "74":75,\n    "75":76,\n    "76":77,\n    "77":78,\n    "78":79,\n    "79":80,\n    "80":81,\n    "81":82,\n    "82":83,\n    "83":84,\n    "84":85\n  },\n  "seek":{\n    "0":0,\n    "1":3000,\n    "2":3000,\n    "3":3000,\n    "4":3000,\n    "5":3000,\n    "6":3000,\n    "7":5600,\n    "8":5600,\n    "9":5600,\n    "10":5600,\n    "11":5600,\n    "12":5600,\n    "13":8100,\n    "14":8100,\n    "15":8100,\n    "16":8100,\n    "17":8100,\n    "18":9700,\n    "19":9700,\n    "20":9700,\n    "21":9700,\n    "22":9700,\n    "23":9700,\n    "24":9700,\n    "25":9700,\n    "26":9700,\n    "27":9700,\n    "28":11900,\n    "29":11900,\n    "30":11900,\n    "31":11900,\n    "32":11900,\n    "33":11900,\n    "34":11900,\n    "35":14600,\n    "36":14600,\n    "37":14600,\n    "38":14600,\n    "39":14600,\n    "40":14600,\n    "41":14600,\n    "42":17100,\n    "43":17100,\n    "44":17100,\n    "45":18800,\n    "46":18800,\n    "47":19800,\n    "48":19800,\n    "49":19800,\n    "50":19800,\n    "51":19800,\n    "52":19800,\n    "53":19800,\n    "54":19800,\n    "55":19800,\n    "56":21900,\n    "57":21900,\n    "58":21900,\n    "59":21900,\n    "60":21900,\n    "61":23400,\n    "62":23400,\n    "63":23400,\n    "64":23400,\n    "65":23400,\n    "66":23400,\n    "67":23400,\n    "68":23400,\n    "69":26400,\n    "70":26400,\n    "71":26400,\n    "72":26400,\n    "73":26400,\n    "74":26400,\n    "75":26400,\n    "76":26400,\n    "77":26400,\n    "78":26400,\n    "79":29300,\n    "80":29300,\n    "81":29300,\n    "82":29300,\n    "83":29300,\n    "84":29300\n  },\n  "start":{\n    "0":0.0,\n    "1":30.0,\n    "2":32.0,\n    "3":36.0,\n    "4":41.0,\n    "5":52.0,\n    "6":54.0,\n    "7":56.0,\n    "8":60.0,\n    "9":63.0,\n    "10":68.0,\n    "11":75.0,\n    "12":79.0,\n    "13":81.0,\n    "14":86.0,\n    "15":88.0,\n    "16":90.0,\n    "17":96.0,\n    "18":97.0,\n    "19":100.0,\n    "20":103.0,\n    "21":104.0,\n    "22":108.0,\n    "23":112.0,\n    "24":114.0,\n    "25":115.0,\n    "26":117.0,\n    "27":118.0,\n    "28":119.0,\n    "29":125.0,\n    "30":134.0,\n    "31":139.0,\n    "32":141.0,\n    "33":143.0,\n    "34":145.0,\n    "35":146.0,\n    "36":150.0,\n    "37":157.0,\n    "38":163.0,\n    "39":165.0,\n    "40":166.0,\n    "41":167.0,\n    "42":171.0,\n    "43":179.0,\n    "44":183.0,\n    "45":188.0,\n    "46":194.0,\n    "47":198.0,\n    "48":199.0,\n    "49":201.0,\n    "50":204.0,\n    "51":206.0,\n    "52":209.0,\n    "53":211.0,\n    "54":213.0,\n    "55":218.0,\n    "56":219.0,\n    "57":223.0,\n    "58":225.0,\n    "59":226.0,\n    "60":229.0,\n    "61":234.0,\n    "62":235.0,\n    "63":242.0,\n    "64":246.0,\n    "65":251.0,\n    "66":253.0,\n    "67":255.0,\n    "68":257.0,\n    "69":265.0,\n    "70":267.0,\n    "71":271.0,\n    "72":273.0,\n    "73":275.0,\n    "74":278.0,\n    "75":284.0,\n    "76":287.0,\n    "77":288.0,\n    "78":290.0,\n    "79":293.0,\n    "80":294.0,\n    "81":298.0,\n    "82":301.0,\n    "83":303.0,\n    "84":305.0\n  },\n  "end":{\n    "0":30.0,\n    "1":32.0,\n    "2":36.0,\n    "3":41.0,\n    "4":50.0,\n    "5":54.0,\n    "6":56.0,\n    "7":60.0,\n    "8":63.0,\n    "9":68.0,\n    "10":71.0,\n    "11":79.0,\n    "12":81.0,\n    "13":86.0,\n    "14":88.0,\n    "15":90.0,\n    "16":96.0,\n    "17":97.0,\n    "18":100.0,\n    "19":103.0,\n    "20":104.0,\n    "21":108.0,\n    "22":111.0,\n    "23":114.0,\n    "24":115.0,\n    "25":117.0,\n    "26":118.0,\n    "27":119.0,\n    "28":125.0,\n    "29":132.0,\n    "30":137.0,\n    "31":140.0,\n    "32":143.0,\n    "33":145.0,\n    "34":146.0,\n    "35":149.0,\n    "36":151.0,\n    "37":163.0,\n    "38":164.0,\n    "39":166.0,\n    "40":167.0,\n    "41":171.0,\n    "42":178.0,\n    "43":182.0,\n    "44":188.0,\n    "45":193.0,\n    "46":198.0,\n    "47":199.0,\n    "48":201.0,\n    "49":204.0,\n    "50":205.0,\n    "51":207.0,\n    "52":210.0,\n    "53":212.0,\n    "54":217.0,\n    "55":219.0,\n    "56":222.0,\n    "57":224.0,\n    "58":226.0,\n    "59":228.0,\n    "60":234.0,\n    "61":235.0,\n    "62":241.0,\n    "63":245.0,\n    "64":250.0,\n    "65":252.0,\n    "66":254.0,\n    "67":256.0,\n    "68":263.0,\n    "69":266.0,\n    "70":270.0,\n    "71":272.0,\n    "72":275.0,\n    "73":277.0,\n    "74":282.0,\n    "75":286.0,\n    "76":288.0,\n    "77":290.0,\n    "78":293.0,\n    "79":294.0,\n    "80":297.0,\n    "81":300.0,\n    "82":302.0,\n    "83":304.0,\n    "84":306.0\n  },\n  "text":{\n    "0":" Это жёлая история Я сегодня хотел с вами поделиться самой странной историей, наверное, в моей жизни Не знаю, может у вас тоже бывали такие ситуации, в которые вы никогда не планировали бы попасть Но жизнь постепенно погружает вас в эту ситуацию Понимаете, о чём я говорю? Короче, ладно, давайте я расскажу историю Я в тот вечер собрался встретиться со своим одноклассником, которым...",\n    "1":" В котором я давно не виделся.",\n    "2":" И мы с ним встретились, пили вино на лестничной клетке.",\n    "3":" Мы были студентами, отрывались по полной.",\n    "4":" Всё было круто, пока в один момент он не созвонился с кем-то и не сказал мне, что сейчас придут боги.",\n    "5":" Боги.",\n    "6":" Боги.",\n    "7":" Я как бы православный человек, понимаете?",\n    "8":" И мне этот момент очень заинтересовал.",\n    "9":" И я остался ждать, естественно, богов, пока они придут.",\n    "10":" Приезжают боги, значит, на лифте.",\n    "11":" Ну, я думаю, кнопки они не нажимали, они же боги всё-таки.",\n    "12":" Я с ними знакомлюсь.",\n    "13":" Ну, у них имена не типа там, а Сирис, там, знаете, как просто типа Лёвик.",\n    "14":" Такие, знаете, чуваки в шортах.",\n    "15":" Вот такие боги.",\n    "16":" И привели ещё девушку какую-то с собой, которая, ну, восхищалась ими не меньше, чем мой одноклассник.",\n    "17":" Понимаете?",\n    "18":" Они прямо души в них не чаяли в этих чуваках.",\n    "19":" Один из них показывал им свои рисунки.",\n    "20":" Типа, посмотрите.",\n    "21":" И мой одноклассник такой, господи, потрясающие рисунки.",\n    "22":" И девушка такая, да, ты начинающий Пикассо.",\n    "23":" Я смотрю, а там обычные рисунки, в принципе.",\n    "24":" Обычные.",\n    "25":" Типа, я такие соскуки рисую на полях в тетради.",\n    "26":" Понимаете?",\n    "27":" Такие рисунки.",\n    "28":" Естественно, они восхищались этими рисунками, потому что для них эти чуваки боги, как бы, да?",\n    "29":" Вряд ли они посмотрели бы на эти рисунки и такие, ну, нет, вы, конечно, боги, но рисунки дерьмо.",\n    "30":" Потом в один момент один из богов достает траву.",\n    "31":" Я опускаю водник.",\n    "32":" Так, этот момент нужно пояснить.",\n    "33":" Я не наркоман.",\n    "34":" Так?",\n    "35":" Я просто...",\n    "36":" Я авантюрист.",\n    "37":" Поймите меня, я тогда был студентом и обоялся пропустить малейший жизненный опыт.",\n    "38":" Даже самый дерьмовый.",\n    "39":" Понимаете?",\n    "40":" И...",\n    "41":" Короче, мне очень плохо стало от этого Спайса.",\n    "42":" И я, типа, сел на пол и понял, что не могу подняться с пола.",\n    "43":" А между тем, вечеринка богов только набирала обороты.",\n    "44":" Один из них достал этот музыкальный инструмент, такую чашу, которая такой звук издавала, типа...",\n    "45":" Музыку включили, которую вводят в транс.",\n    "46":" И один из них, насколько я понял, главный бог, начал читать свои стихи.",\n    "47":" Вот.",\n    "48":" И в этот момент мне стало что-то стрёмно.",\n    "49":" Потому что я был заложником ситуации.",\n    "50":" Я не могу встать.",\n    "51":" Передо мной боги.",\n    "52":" И я чувствую прямо...",\n    "53":" Понимаете? Я прямо чувствовал в тот момент,",\n    "54":" как они пытаются эти стихи воздействовать на мое мировоззрение.",\n    "55":" Понимаете?",\n    "56":" Я чувствую себя, как он говорит, что его друга, и он прямо кайфует от этих стихов.",\n    "57":" Он прямо не может нарадоваться.",\n    "58":" Вот.",\n    "59":" И мне было очень страшно, потому что я был таким заложником.",\n    "60":" Но в какой-то момент я все-таки нашел себе силы встать и выйти на балкон и проблеваться.",\n    "61":" Вот что я понял.",\n    "62":" Вот насколько во мне сильная православная вера.",\n    "63":" Что она выплевала из меня...",\n    "64":" Что выплевала из меня чужие убеждения.",\n    "65":" Понимаете?",\n    "66":" Да, я остался православным.",\n    "67":" Вот такое мое достижение.",\n    "68":" Но с другой стороны, я сейчас стою перед группой людей и вещаю о этих богах, как пророк самый настоящий.",\n    "69":" Странно.",\n    "70":" Но, ребят, если вы до сих пор задаетесь вопросом,",\n    "71":" такими вопросами, типа,",\n    "72":" почему там дети в Африке голодают,",\n    "73":" или почему войны не заканчиваются.",\n    "74":" Может потому что боги все это время курят спайс на лестничной клетке.",\n    "75":" На этом все. Спасибо. Пока.",\n    "76":" В следующем выпуске.",\n    "77":" Мы были очень близкими друзьями. Очень близкими.",\n    "78":" И знаете, когда друзья становятся очень близки друг к другу,",\n    "79":" они обычно делают что-то совместное.",\n    "80":" Типа, давайте все сделаем одну и ту же татуировку.",\n    "81":" Давайте все сделаем одни и те же шрамы на руках.",\n    "82":" Мы решили сделать что-то подобное,",\n    "83":" только мы начали...",\n    "84":" сосаться друг с другом."\n  },\n  "tokens":{\n    "0":[\n      50365,\n      6684,\n      2989,\n      24180,\n      4251,\n      41531,\n      13,\n      50492\n    ],\n    "1":[\n      50365,\n      2348,\n      39818,\n      2552,\n      40086,\n      1725,\n      40718,\n      1679,\n      13,\n      50465\n    ],\n    "2":[\n      50465,\n      3272,\n      4777,\n      776,\n      25793,\n      47647,\n      19285,\n      11,\n      713,\n      5435,\n      28570,\n      1234,\n      1470,\n      2344,\n      5740,\n      27996,\n      5007,\n      14815,\n      1094,\n      8222,\n      13,\n      50665\n    ],\n    "3":[\n      50665,\n      12726,\n      14355,\n      44322,\n      5243,\n      5150,\n      11,\n      2943,\n      17702,\n      15020,\n      2801,\n      4692,\n      5007,\n      13,\n      50915\n    ],\n    "4":[\n      50915,\n      29661,\n      8060,\n      26970,\n      860,\n      11,\n      17770,\n      740,\n      13319,\n      17825,\n      5345,\n      1725,\n      14729,\n      39672,\n      14260,\n      776,\n      981,\n      1504,\n      12,\n      860,\n      1006,\n      1725,\n      24980,\n      8531,\n      11,\n      2143,\n      10241,\n      21255,\n      3767,\n      33001,\n      435,\n      13,\n      51365\n    ],\n    "5":[\n      51465,\n      34008,\n      435,\n      13,\n      51565\n    ],\n    "6":[\n      51565,\n      34008,\n      435,\n      13,\n      51665\n    ],\n    "7":[\n      50365,\n      4857,\n      3014,\n      2768,\n      10615,\n      1885,\n      22810,\n      4441,\n      11326,\n      11,\n      15084,\n      17670,\n      30,\n      50565\n    ],\n    "8":[\n      50565,\n      3272,\n      8531,\n      11508,\n      17825,\n      6730,\n      4396,\n      2599,\n      45453,\n      31731,\n      13,\n      50715\n    ],\n    "9":[\n      50715,\n      3272,\n      2552,\n      12574,\n      13340,\n      27020,\n      2209,\n      11,\n      43775,\n      17125,\n      11,\n      33001,\n      1055,\n      11,\n      17770,\n      7515,\n      21255,\n      3767,\n      13,\n      50965\n    ],\n    "10":[\n      50965,\n      22059,\n      32682,\n      6406,\n      33001,\n      435,\n      11,\n      24013,\n      11,\n      1470,\n      7444,\n      3619,\n      5863,\n      13,\n      51115\n    ],\n    "11":[\n      51315,\n      7571,\n      11,\n      2552,\n      23479,\n      11,\n      40450,\n      2241,\n      7515,\n      1725,\n      35675,\n      2165,\n      4071,\n      11,\n      7515,\n      6151,\n      33001,\n      435,\n      9649,\n      12,\n      27430,\n      13,\n      51515\n    ],\n    "12":[\n      51515,\n      4857,\n      776,\n      42371,\n      40909,\n      6578,\n      6131,\n      13,\n      51615\n    ],\n    "13":[\n      50365,\n      7571,\n      11,\n      1595,\n      14319,\n      7604,\n      13362,\n      1725,\n      35443,\n      8223,\n      11,\n      2559,\n      2933,\n      4490,\n      3323,\n      11,\n      8223,\n      11,\n      29868,\n      11,\n      3014,\n      8221,\n      35443,\n      7853,\n      2882,\n      859,\n      3605,\n      13,\n      50615\n    ],\n    "14":[\n      50615,\n      8770,\n      5299,\n      11,\n      29868,\n      11,\n      22472,\n      48877,\n      740,\n      5941,\n      20040,\n      7004,\n      13,\n      50715\n    ],\n    "15":[\n      50715,\n      9756,\n      20113,\n      33001,\n      435,\n      13,\n      50815\n    ],\n    "16":[\n      50815,\n      3272,\n      13398,\n      8334,\n      13993,\n      20572,\n      8288,\n      4401,\n      45244,\n      12,\n      860,\n      776,\n      32474,\n      11,\n      19032,\n      11,\n      13087,\n      11,\n      18867,\n      1157,\n      22280,\n      19711,\n      1006,\n      6293,\n      1725,\n      35115,\n      11,\n      12056,\n      23400,\n      5693,\n      48717,\n      693,\n      12886,\n      9715,\n      13,\n      51115\n    ],\n    "17":[\n      51115,\n      36067,\n      2165,\n      17670,\n      30,\n      51165\n    ],\n    "18":[\n      50365,\n      18973,\n      28547,\n      39096,\n      435,\n      740,\n      14319,\n      1725,\n      1358,\n      4251,\n      1675,\n      740,\n      23296,\n      22472,\n      1272,\n      7004,\n      13,\n      50515\n    ],\n    "19":[\n      50515,\n      20125,\n      2599,\n      3943,\n      14319,\n      34614,\n      1218,\n      7604,\n      25375,\n      31393,\n      12161,\n      2241,\n      13,\n      50665\n    ],\n    "20":[\n      50665,\n      3200,\n      13306,\n      386,\n      11,\n      19240,\n      5878,\n      13,\n      50715\n    ],\n    "21":[\n      50715,\n      3272,\n      23400,\n      5693,\n      48717,\n      693,\n      12886,\n      9715,\n      13452,\n      11,\n      6778,\n      6461,\n      1435,\n      435,\n      11,\n      26146,\n      15293,\n      18718,\n      5299,\n      31393,\n      12161,\n      2241,\n      13,\n      50915\n    ],\n    "22":[\n      50915,\n      3272,\n      20572,\n      34187,\n      22075,\n      11,\n      8995,\n      11,\n      5991,\n      21995,\n      24219,\n      6251,\n      2608,\n      3605,\n      12886,\n      354,\n      13,\n      51065\n    ],\n    "23":[\n      51115,\n      4857,\n      17726,\n      1148,\n      11,\n      2559,\n      8223,\n      32291,\n      4970,\n      31393,\n      12161,\n      2241,\n      11,\n      740,\n      39086,\n      13,\n      51215\n    ],\n    "24":[\n      51215,\n      22853,\n      21097,\n      4970,\n      13,\n      51265\n    ],\n    "25":[\n      51265,\n      3200,\n      13306,\n      386,\n      11,\n      2552,\n      20113,\n      33165,\n      4401,\n      2241,\n      31393,\n      3924,\n      1470,\n      4692,\n      24725,\n      740,\n      1069,\n      42850,\n      18389,\n      13,\n      51365\n    ],\n    "26":[\n      51365,\n      36067,\n      2165,\n      17670,\n      30,\n      51415\n    ],\n    "27":[\n      51415,\n      8770,\n      5299,\n      31393,\n      12161,\n      2241,\n      13,\n      51465\n    ],\n    "28":[\n      50365,\n      6538,\n      27492,\n      17125,\n      11,\n      7515,\n      18867,\n      1157,\n      22280,\n      15020,\n      4030,\n      11426,\n      31393,\n      12161,\n      22379,\n      11,\n      11919,\n      2143,\n      5561,\n      14319,\n      11012,\n      22472,\n      48877,\n      33001,\n      435,\n      11,\n      3014,\n      2768,\n      11,\n      8995,\n      30,\n      50665\n    ],\n    "29":[\n      50665,\n      2348,\n      44447,\n      7444,\n      7515,\n      19240,\n      8334,\n      2768,\n      1470,\n      11012,\n      31393,\n      12161,\n      2241,\n      1006,\n      20113,\n      11,\n      13087,\n      11,\n      9916,\n      11,\n      2840,\n      11,\n      15271,\n      11,\n      33001,\n      435,\n      11,\n      6035,\n      31393,\n      12161,\n      2241,\n      1070,\n      9352,\n      20455,\n      13,\n      51015\n    ],\n    "30":[\n      51115,\n      45941,\n      740,\n      13319,\n      17825,\n      13319,\n      3943,\n      33001,\n      1055,\n      34543,\n      3310,\n      46647,\n      585,\n      13,\n      51265\n    ],\n    "31":[\n      51365,\n      4857,\n      7683,\n      33101,\n      1148,\n      14545,\n      9715,\n      13,\n      51415\n    ],\n    "32":[\n      51465,\n      8770,\n      11,\n      11508,\n      17825,\n      12264,\n      2801,\n      15293,\n      31087,\n      13,\n      51565\n    ],\n    "33":[\n      51565,\n      4857,\n      1725,\n      34316,\n      14937,\n      1416,\n      13,\n      51665\n    ],\n    "34":[\n      51665,\n      8770,\n      30,\n      51715\n    ],\n    "35":[\n      50365,\n      4857,\n      8221,\n      485,\n      50515\n    ],\n    "36":[\n      50565,\n      4857,\n      14376,\n      15073,\n      1148,\n      39085,\n      13,\n      50615\n    ],\n    "37":[\n      50915,\n      2608,\n      1700,\n      919,\n      5878,\n      6885,\n      11,\n      2552,\n      21696,\n      10059,\n      44322,\n      5243,\n      1253,\n      1006,\n      3348,\n      354,\n      16065,\n      1679,\n      23497,\n      46937,\n      19499,\n      2345,\n      24958,\n      13505,\n      489,\n      28488,\n      48530,\n      13,\n      51215\n    ],\n    "38":[\n      51215,\n      42900,\n      30688,\n      1070,\n      9352,\n      43632,\n      4851,\n      13,\n      51265\n    ],\n    "39":[\n      51315,\n      36067,\n      2165,\n      17670,\n      30,\n      51365\n    ],\n    "40":[\n      51365,\n      3272,\n      485,\n      51415\n    ],\n    "41":[\n      51415,\n      29635,\n      39649,\n      11,\n      8531,\n      6730,\n      45210,\n      39633,\n      2943,\n      10751,\n      19349,\n      3183,\n      22568,\n      13,\n      51615\n    ],\n    "42":[\n      50365,\n      3272,\n      2552,\n      11,\n      35443,\n      11,\n      776,\n      1414,\n      1470,\n      4692,\n      1006,\n      37975,\n      11,\n      2143,\n      1725,\n      22951,\n      4095,\n      5151,\n      14706,\n      776,\n      4692,\n      386,\n      13,\n      50715\n    ],\n    "43":[\n      50765,\n      3450,\n      24098,\n      12532,\n      11,\n      31943,\n      1135,\n      2599,\n      2833,\n      33001,\n      1055,\n      9008,\n      22499,\n      4490,\n      6232,\n      3348,\n      37040,\n      698,\n      13,\n      50915\n    ],\n    "44":[\n      50965,\n      20125,\n      2599,\n      3943,\n      14319,\n      34543,\n      1218,\n      11508,\n      34249,\n      755

In [5]:
import pandas as pd
from io import StringIO

df = pd.read_json(StringIO(result))
df

,id,seek,start,end,text,tokens,temperature,avg_logprob,compression_ratio,no_speech_prob,words,next_start
0,0,0,0,30,Это жёлая история Я сегодня хотел с вами поде...,"[50365, 6684, 2989, 24180, 4251, 41531, 13, 50...",0,-0.653411,0.825000,0,NaN,30.0
1,1,3000,30,32,В котором я давно не виделся.,"[50365, 2348, 39818, 2552, 40086, 1725, 40718,...",0,-0.240090,1.821277,0,NaN,2.0
2,2,3000,32,36,"И мы с ним встретились, пили вино на лестничн...","[50465, 3272, 4777, 776, 25793, 47647, 19285, ...",0,-0.240090,1.821277,0,NaN,4.0
3,3,3000,36,41,"Мы были студентами, отрывались по полной.","[50665, 12726, 14355, 44322, 5243, 5150, 11, 2...",0,-0.240090,1.821277,0,NaN,5.0
4,4,3000,41,50,"Всё было круто, пока в один момент он не созв...","[50915, 29661, 8060, 26970, 860, 11, 17770, 74...",0,-0.240090,1.821277,0,NaN,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...
80,81,29300,294,297,"Типа, давайте все сделаем одну и ту же татуир...","[50415, 3200, 13306, 386, 11, 30412, 4640, 103...",0,-0.138512,1.846154,0,NaN,4.0
81,82,29300,298,300,Давайте все сделаем одни и те же шрамы на руках.,"[50615, 30487, 4640, 10326, 7906, 5693, 1903, ...",0,-0.138512,1.846154,0,NaN,3.0
82,83,29300,301,302,"Мы решили сделать что-то подобное,","[50765, 12726, 14025, 5435, 18695, 2143, 12, 8...",0,-0.138512,1.846154,0,NaN,2.0
83,84,29300,303,304,только мы начали...,"[50865, 9008, 4777, 8970, 4071, 485, 50915]",0,-0.138512,1.846154,0,NaN,2.0
84,85,29300,305,306,сосаться друг с другом.,"[50965, 33165, 8525, 8435, 776, 8435, 1253, 13...",0,-0.138512,1.846154,0,NaN,NaN

In [4]:
import pandas as pd
from io import StringIO

df = pd.read_json(StringIO(result))

# Округляем колонку 'start' до целого
df["start"] = df["start"].round().astype(int)

# Выбираем только нужные колонки
df_export = df[["start", "text"]]

# Сохраняем в TSV-файл
text = df_export.to_csv(sep="\t", index=False)
text

'start\ttext\n0\t Это жёлая история Я сегодня хотел с вами поделиться самой странной историей, наверное, в моей жизни Не знаю, может у вас тоже бывали такие ситуации, в которые вы никогда не планировали бы попасть Но жизнь постепенно погружает вас в эту ситуацию Понимаете, о чём я говорю? Короче, ладно, давайте я расскажу историю Я в тот вечер собрался встретиться со своим одноклассником, которым...\n30\t В котором я давно не виделся.\n32\t И мы с ним встретились, пили вино на лестничной клетке.\n36\t Мы были студентами, отрывались по полной.\n41\t Всё было круто, пока в один момент он не созвонился с кем-то и не сказал мне, что сейчас придут боги.\n52\t Боги.\n54\t Боги.\n56\t Я как бы православный человек, понимаете?\n60\t И мне этот момент очень заинтересовал.\n63\t И я остался ждать, естественно, богов, пока они придут.\n68\t Приезжают боги, значит, на лифте.\n75\t Ну, я думаю, кнопки они не нажимали, они же боги всё-таки.\n79\t Я с ними знакомлюсь.\n81\t Ну, у них имена не типа там, а Сирис, там, знаете, как просто типа Лёвик.\n86\t Такие, знаете, чуваки в шортах.\n88\t Вот такие боги.\n90\t И привели ещё девушку какую-то с собой, которая, ну, восхищалась ими не меньше, чем мой одноклассник.\n96\t Понимаете?\n97\t Они прямо души в них не чаяли в этих чуваках.\n100\t Один из них показывал им свои рисунки.\n103\t Типа, посмотрите.\n104\t И мой одноклассник такой, господи, потрясающие рисунки.\n108\t И девушка такая, да, ты начинающий Пикассо.\n112\t Я смотрю, а там обычные рисунки, в принципе.\n114\t Обычные.\n115\t Типа, я такие соскуки рисую на полях в тетради.\n117\t Понимаете?\n118\t Такие рисунки.\n119\t Естественно, они восхищались этими рисунками, потому что для них эти чуваки боги, как бы, да?\n125\t Вряд ли они посмотрели бы на эти рисунки и такие, ну, нет, вы, конечно, боги, но рисунки дерьмо.\n134\t Потом в один момент один из богов достает траву.\n139\t Я опускаю водник.\n141\t Так, этот момент нужно пояснить.\n143\t Я не наркоман.\n145\t Так?\n146\t Я просто...\n150\t Я авантюрист.\n157\t Поймите меня, я тогда был студентом и обоялся пропустить малейший жизненный опыт.\n163\t Даже самый дерьмовый.\n165\t Понимаете?\n166\t И...\n167\t Короче, мне очень плохо стало от этого Спайса.\n171\t И я, типа, сел на пол и понял, что не могу подняться с пола.\n179\t А между тем, вечеринка богов только набирала обороты.\n183\t Один из них достал этот музыкальный инструмент, такую чашу, которая такой звук издавала, типа...\n188\t Музыку включили, которую вводят в транс.\n194\t И один из них, насколько я понял, главный бог, начал читать свои стихи.\n198\t Вот.\n199\t И в этот момент мне стало что-то стрёмно.\n201\t Потому что я был заложником ситуации.\n204\t Я не могу встать.\n206\t Передо мной боги.\n209\t И я чувствую прямо...\n211\t Понимаете? Я прямо чувствовал в тот момент,\n213\t как они пытаются эти стихи воздействовать на мое мировоззрение.\n218\t Понимаете?\n219\t Я чувствую себя, как он говорит, что его друга, и он прямо кайфует от этих стихов.\n223\t Он прямо не может нарадоваться.\n225\t Вот.\n226\t И мне было очень страшно, потому что я был таким заложником.\n229\t Но в какой-то момент я все-таки нашел себе силы встать и выйти на балкон и проблеваться.\n234\t Вот что я понял.\n235\t Вот насколько во мне сильная православная вера.\n242\t Что она выплевала из меня...\n246\t Что выплевала из меня чужие убеждения.\n251\t Понимаете?\n253\t Да, я остался православным.\n255\t Вот такое мое достижение.\n257\t Но с другой стороны, я сейчас стою перед группой людей и вещаю о этих богах, как пророк самый настоящий.\n265\t Странно.\n267\t Но, ребят, если вы до сих пор задаетесь вопросом,\n271\t такими вопросами, типа,\n273\t почему там дети в Африке голодают,\n275\t или почему войны не заканчиваются.\n278\t Может потому что боги все это время курят спайс на лестничной клетке.\n284\t На этом все. Спасибо. Пока.\n287\t В следующем выпуске.\n288\t Мы были очень близкими друзьями. Очень близкими.\n290\t И знаете, когда друзья становятся очень близки друг к другу,\n293\t они обычно делают что-то совместное.\n294\t Типа, давайте все сделаем одну и ту же татуировку.\n298\t Давайте все сделаем одни и те же шрамы на руках.\n301\t Мы решили сделать что-то подобное,\n303\t только мы начали...\n305\t сосаться друг с другом.\n'