# Терминал

Коваль:
https://www.youtube.com/watch?v=ys6VjUnWQCk
https://www.youtube.com/watch?v=U6CkCnJYhcU
https://www.youtube.com/watch?v=idUkymOQYJs
https://www.youtube.com/watch?v=OFhwMqXeQUE

Ахмедова:
https://www.youtube.com/watch?v=WC8MGi_sItE
https://www.youtube.com/watch?v=v1xb76zn2WQ

АРИАНА ЛОЛАЕВА:
https://www.youtube.com/watch?v=fdx7m7tgXdQ

Аранова Елизавета Варвара
https://www.youtube.com/watch?v=wAy_XfHCfuA

Слава Комиссаренко
https://www.youtube.com/watch?v=ExrG6AhR-wI
https://www.youtube.com/watch?v=k8Mixx5Q4vc

Алексей Квашонкин
https://www.youtube.com/watch?v=7GAr9pJeIp0

In [2]:
from pathlib import Path

url = "https://www.youtube.com/watch?v=OFhwMqXeQUE"


audio_path = "../data/!Notebook_test/audio/Idrak_first2.wav"
audio_name = Path(audio_path).stem

transcribe_path = "../data/!Notebook_test/transcripts_with_timestamp/"

print(transcribe_path + audio_name + ".json")

../data/!Notebook_test/transcripts_with_timestamp/Idrak_first2.json

# Тестирование отдельных функций

## Транскрибация локального аудиофайла в переменную (словарь)

In [3]:
import mlx_whisper

result = mlx_whisper.transcribe(
    str(audio_path),
    path_or_hf_repo="mlx-community/whisper-large-v3-turbo",
)

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

In [3]:
result

{'text': ' Какие у вас политические взгляды? Вот всегда-всегда вот такой нервный смешок. Но я вас понимаю, я тоже не распространяюсь о своих политических взглядах, но из-за того, что я немного медийный, обо мне иногда пишут, я про себя прочитал вот такое вот. Левацкое отродье. Вот так написали. И мне не понравилось, потому что я сам не уверен, кто я, решил загуглить, как понять, какие у тебя политические взгляды. И мне попалась там диаграмма политических взглядов. Вам попадалось такое? Диаграмма, по которой ты определяешь, кто ты. И оказалось, что я ультраправый радикал вообще. По многим взглядам совпало, например, отношение к гомосексуализму. У меня такое уже крайне негативное. Взять, если там лесбиянок, например. Я вообще не пойму, как можно хотеть женщин. Для меня это загадка. Или, например, отношение к эмигрантам. Я вот сам, как только, я три года назад переехал в Европу. Я как только переехал, я подумал, закрывайте ворота, нам эти обезьяны тут не нужны. Мы не для того, да, приехали в Европу, чтобы кто-то еще туда приезжал, вонял там на улицах. Для нас, европейцев, это неприемлемо уже. Ну и понятно, кроме меня никто европейские проблемы решать не собирается. Я решил получить паспорт Германии, потому что его сейчас легче всего получить. Решил получить паспорт Германии, чтобы голосовать исключительно за правые партии. Чтобы нашу Германию очистить от мусора. Потому что для меня, да, потому что для меня Германия превыше всего сейчас. Ну и естественно нужно определиться со своим национализмом. Пора понять, за кого я готов убивать.',
 'segments': [{'id': 0,
   'seek': 0,
   'start': 0.0,
   'end': 6.54,
   'text': ' Какие у вас политические взгляды? Вот всегда-всегда вот такой нервный смешок. Но я вас понимаю, я тоже не',
   'tokens': [50365,
    11011,
    5299,
    1595,
    10655,
    45330,
    38578,
    11892,
    22232,
    698,
    30,
    9756,
    19087,
    12,
    859,
    461,
    17540,
    5505,
    13452,
    757,
    36441,
    4441,
    6871,
    4433,
    2637,
    13,
    7264,
    2552,
    10655,
    35112,
    11,
    2552,
    12251,
    1725,
    50692],
   'temperature': 0.0,
   'avg_logprob': -0.1479472999113152,
   'compression_ratio': 2.319693094629156,
   'no_speech_prob': 2.3833674617224077e-11},
  {'id': 1,
   'seek': 0,
   'start': 6.54,
   'end': 12.0,
   'text': ' распространяюсь о своих политических взглядах, но из-за того, что я немного медийный, обо мне иногда',
   'tokens': [50692,
    26588,
    9938,
    28484,
    681,
    24551,
    1000,
    30316,
    45330,
    38911,
    11892,
    18720,
    3444,
    1157,
    11,
    6035,
    3943,
    12,
    18598,
    11283,
    11,
    2143,
    2552,
    26583,
    24465,
    6251,
    4441,
    11,
    3348,
    354,
    8531,
    43749,
    50965],
   'temperature': 0.0,
   'avg_logprob': -0.1479472999113152,
   'compression_ratio': 2.319693094629156,
   'no_speech_prob': 2.3833674617224077e-11},
  {'id': 2,
   'seek': 0,
   'start': 12.0,
   'end': 18.48,
   'text': ' пишут, я про себя прочитал вот такое вот. Левацкое отродье. Вот так написали. И мне не понравилось,',
   'tokens': [50965,
    37979,
    3767,
    11,
    2552,
    4178,
    15403,
    4178,
    9607,
    1218,
    5505,
    18292,
    5505,
    13,
    7853,
    3515,
    32507,
    22128,
    2943,
    10004,
    46176,
    13,
    9756,
    2936,
    30442,
    4071,
    13,
    3272,
    8531,
    1725,
    34752,
    16773,
    11,
    51289],
   'temperature': 0.0,
   'avg_logprob': -0.1479472999113152,
   'compression_ratio': 2.319693094629156,
   'no_speech_prob': 2.3833674617224077e-11},
  {'id': 3,
   'seek': 0,
   'start': 18.48,
   'end': 23.52,
   'text': ' потому что я сам не уверен, кто я, решил загуглить, как понять, какие у тебя политические взгляды. И мне',
   'tokens': [51289,
    11919,
    2143,
    2552,
    5602,
    1725,
    32838,
    1008,
    11,
    12278,
    2552,
    11,
    44240,
    25770,
    22638,
    1675,
    1283,
    11,
    3014,
    44403,
    11,
    19971,
    1595,
    12644,
    45330,
    38578,
    11892,
    22232,
    698,
    13,
    3272,
    8531,
    51541],
   'temperature': 0.0,
   'avg_logprob': -0.1479472999113152,
   'compression_ratio': 2.319693094629156,
   'no_speech_prob': 2.3833674617224077e-11},
  {'id': 4,
   'seek': 0,
   'start': 23.52,
   'end': 27.96,
   'text': ' попалась там диаграмма политических взглядов. Вам попадалось такое? Диаграмма, по которой ты',
   'tokens': [51541,
    10694,
    19711,
    8223,
    28255,
    5583,
    15837,
    14229,
    45330,
    38911,
    11892,
    22232,
    1055,
    13,
    43670,
    43613,
    16122,
    18292,
    30,
    3401,
    435,
    5583,
    15837,
    14229,
    11,
    2801,
    29452,
    5991,
    51763],
   'temperature': 0.0,
   'avg_logprob': -0.1479472999113152,
   'compression_ratio': 2.319693094629156,
   'no_speech_prob': 2.3833674617224077e-11},
  {'id': 5,
   'seek': 2796,
   'start': 27.96,
   'end': 35.58,
   'text': ' определяешь, кто ты. И оказалось, что я ультраправый радикал вообще. По многим взглядам совпало,',
   'tokens': [50365,
    26961,
    15292,
    7815,
    11,
    12278,
    5991,
    13,
    3272,
    28833,
    16122,
    11,
    2143,
    2552,
    1595,
    6762,
    13981,
    4219,
    5608,
    4851,
    26622,
    3605,
    1218,
    14345,
    13,
    12121,
    22287,
    2165,
    11892,
    22232,
    1685,
    11030,
    1354,
    12441,
    11,
    50746],
   'temperature': 0.0,
   'avg_logprob': -0.10542776978131636,
   'compression_ratio': 1.8374558303886925,
   'no_speech_prob': 1.0259139024415553e-11},
  {'id': 6,
   'seek': 2796,
   'start': 35.58,
   'end': 42.06,
   'text': ' например, отношение к гомосексуализму. У меня такое уже крайне негативное. Взять, если там',
   'tokens': [50746,
    24044,
    11,
    30708,
    5627,
    981,
    2342,
    1253,
    1885,
    38269,
    585,
    28105,
    11147,
    13,
    6523,
    6885,
    18292,
    7520,
    39584,
    4677,
    757,
    4953,
    30875,
    6126,
    13,
    2348,
    1544,
    8773,
    11,
    8042,
    8223,
    51070],
   'temperature': 0.0,
   'avg_logprob': -0.10542776978131636,
   'compression_ratio': 1.8374558303886925,
   'no_speech_prob': 1.0259139024415553e-11},
  {'id': 7,
   'seek': 2796,
   'start': 42.06,
   'end': 53.58,
   'text': ' лесбиянок, например. Я вообще не пойму, как можно хотеть женщин. Для меня это загадка. Или, например,',
   'tokens': [51070,
    42548,
    1552,
    7409,
    48717,
    11,
    24044,
    13,
    4857,
    14345,
    1725,
    31671,
    11147,
    11,
    3014,
    8885,
    11515,
    9108,
    28393,
    2599,
    13,
    21324,
    6885,
    2691,
    25770,
    2601,
    2833,
    13,
    34361,
    11,
    24044,
    11,
    51646],
   'temperature': 0.0,
   'avg_logprob': -0.10542776978131636,
   'compression_ratio': 1.8374558303886925,
   'no_speech_prob': 1.0259139024415553e-11},
  {'id': 8,
   'seek': 5358,
   'start': 53.58,
   'end': 59.16,
   'text': ' отношение к эмигрантам. Я вот сам, как только, я три года назад переехал в Европу. Я как только',
   'tokens': [50365,
    30708,
    5627,
    981,
    1704,
    6293,
    7786,
    15073,
    1685,
    13,
    4857,
    5505,
    5602,
    11,
    3014,
    9008,
    11,
    2552,
    22068,
    18411,
    28724,
    4321,
    7752,
    1157,
    1218,
    740,
    34019,
    26090,
    585,
    13,
    4857,
    3014,
    9008,
    50644],
   'temperature': 0.0,
   'avg_logprob': -0.11934707959493002,
   'compression_ratio': 1.9305555555555556,
   'no_speech_prob': 1.632505242099569e-11},
  {'id': 9,
   'seek': 5358,
   'start': 59.16,
   'end': 67.92,
   'text': ' переехал, я подумал, закрывайте ворота, нам эти обезьяны тут не нужны. Мы не для того, да, приехали в Европу,',
   'tokens': [50644,
    4321,
    7752,
    1157,
    1218,
    11,
    2552,
    38664,
    1218,
    11,
    10264,
    17702,
    10330,
    740,
    1717,
    26808,
    11,
    11401,
    11012,
    3348,
    3634,
    14195,
    1834,
    12848,
    1725,
    9353,
    1834,
    13,
    12726,
    1725,
    5561,
    11283,
    11,
    8995,
    11,
    38567,
    4071,
    740,
    34019,
    26090,
    585,
    11,
    51082],
   'temperature': 0.0,
   'avg_logprob': -0.11934707959493002,
   'compression_ratio': 1.9305555555555556,
   'no_speech_prob': 1.632505242099569e-11},
  {'id': 10,
   'seek': 5358,
   'start': 67.92,
   'end': 76.86,
   'text': ' чтобы кто-то еще туда приезжал, вонял там на улицах. Для нас, европейцев, это неприемлемо уже. Ну и понятно,',
   'tokens': [51082,
    7887,
    12278,
    12,
    860,
    9910,
    30433,
    5082,
    32682,
    1218,
    11,
    740,
    1784,
    16065,
    8223,
    1470,
    36639,
    1814,
    7004,
    13,
    21324,
    6519,
    11,
    42402,
    26090,
    2345,
    22898,
    11,
    2691,
    17005,
    4679,
    1504,
    14885,
    354,
    7520,
    13,
    7571,
    1006,
    39718,
    11,
    51529],
   'temperature': 0.0,
   'avg_logprob': -0.11934707959493002,
   'compression_ratio': 1.9305555555555556,
   'no_speech_prob': 1.632505242099569e-11},
  {'id': 11,
   'seek': 7686,
   'start': 76.86,
   'end': 84.0,
   'text': ' кроме меня никто европейские проблемы решать не собирается. Я решил получить паспорт Германии,',
   'tokens': [50365,
    7502,
    45540,
    6885,
    31666,
    42402,
    26090,
    2345,
    25254,
    44340,
    14025,
    2209,
    1725,
    41534,
    6970,
    13,
    4857,
    44240,
    41725,
    713,
    2019,
    1354,
    20040,
    7247,
    49483,
    16426,
    11,
    50722],
   'temperature': 0.0,
   'avg_logprob': -0.08280266290423514,
   'compression_ratio': 2.0890688259109313,
   'no_speech_prob': 1.4076824775277608e-11},
  {'id': 12,
   'seek': 7686,
   'start': 84.0,
   'end': 88.68,
   'text': ' потому что его сейчас легче всего получить. Решил получить паспорт Германии, чтобы голосовать',
   'tokens': [50722,
    11919,
    2143,
    6448,
    10241,
    22311,
    32595,
    15520,
    41725,
    13,
    6325,
    4433,
    2338,
    41725,
    713,
    2019,
    1354,
    20040,
    7247,
    49483,
    16426,
    11,
    7887,
    42390,
    14069,
    50956],
   'temperature': 0.0,
   'avg_logprob': -0.08280266290423514,
   'compression_ratio': 2.0890688259109313,
   'no_speech_prob': 1.4076824775277608e-11},
  {'id': 13,
   'seek': 7686,
   'start': 88.68,
   'end': 101.1,
   'text': ' исключительно за правые партии. Чтобы нашу Германию очистить от мусора. Потому что для меня,',
   'tokens': [50956,
    20284,
    11833,
    15884,
    4396,
    10615,
    5312,
    11813,
    3396,
    435,
    13,
    36026,
    8253,
    585,
    7247,
    49483,
    34537,
    5875,
    9330,
    3258,
    2943,
    1084,
    7071,
    22889,
    13,
    23671,
    2143,
    5561,
    6885,
    11,
    51577],
   'temperature': 0.0,
   'avg_logprob': -0.08280266290423514,
   'compression_ratio': 2.0890688259109313,
   'no_speech_prob': 1.4076824775277608e-11},
  {'id': 14,
   'seek': 10110,
   'start': 101.1,
   'end': 112.32,
   'text': ' да, потому что для меня Германия превыше всего сейчас. Ну и естественно нужно определиться со своим',
   'tokens': [50365,
    8995,
    11,
    11919,
    2143,
    5561,
    6885,
    7247,
    49483,
    8831,
    34393,
    698,
    5246,
    15520,
    10241,
    13,
    7571,
    1006,
    43775,
    17125,
    12264,
    39305,
    12306,
    7425,
    37337,
    50926],
   'temperature': 0.0,
   'avg_logprob': -0.17419099807739258,
   'compression_ratio': 1.5771428571428572,
   'no_speech_prob': 1.3847598415162032e-11},
  {'id': 15,
   'seek': 10110,
   'start': 112.32,
   'end': 115.32,
   'text': ' национализмом. Пора понять, за кого я готов убивать.',
   'tokens': [50926,
    1470,
    21964,
    28105,
    919,
    1253,
    13,
    2608,
    22889,
    44403,
    11,
    4396,
    28985,
    2552,
    17137,
    13853,
    20566,
    13,
    51076],
   'temperature': 0.0,
   'avg_logprob': -0.17419099807739258,
   'compression_ratio': 1.5771428571428572,
   'no_speech_prob': 1.3847598415162032e-11}],
 'language': 'ru'}

## Фильтрация словаря,получение только нужных колонок

In [10]:
filtered_result = {
    "text": result["text"],
    "segments": [
        {
            "id": segment["id"],
            "start": segment["start"],
            "end": segment["end"],
            "text": segment["text"],
        }
        for segment in result.get("segments", [])
    ],
}

In [11]:
filtered_result

{'text': ' Какие у вас политические взгляды? Вот всегда-всегда вот такой нервный смешок. Но я вас понимаю, я тоже не распространяюсь о своих политических взглядах, но из-за того, что я немного медийный, обо мне иногда пишут, я про себя прочитал вот такое вот. Левацкое отродье. Вот так вот. И мне не понравилось, потому что я сам не уверен, кто я, решил загуглить, как понять, какие у тебя политические взгляды. И мне попалась там диаграмма политических взглядов. Вам попадалось такое? Диаграмма, по которой ты определяешь, кто ты. И оказалось, что я ультраправый радикал вообще. По многим взглядам совпало, например, отношение к гомосексуализму. У меня такое уже крайне негативное. Взять, если там лесбиянок, например. Я вообще не пойму, как можно хотеть женщин. Для меня это загадка. Или, например, отношение к эмигрантам. Я вот сам, как только, я три года назад переехал в Европу. Я как только переехал, я подумал, закрывайте ворота, нам эти обезьяны тут не нужны. Мы не для того, да, приехали в Европу, чтобы кто-то еще туда приезжал, вонял там на улицах. Для нас, европейцев, это неприемлемо уже. Ну и понятно, кроме меня никто европейские проблемы решать не собирается. Я решил получить паспорт Германии, потому что его сейчас легче всего получить. Решил получить паспорт Германии, чтобы голосовать исключительно за правые партии. Чтобы нашу Германию очистить от мусора. Потому что для меня, да, потому что для меня Германия превыше всего сейчас. Ну и естественно нужно определиться со своим национализмом. Пора понять, за кого я готов убивать.',
 'segments': [{'id': 0,
   'start': 0.0,
   'end': 6.5600000000000005,
   'text': ' Какие у вас политические взгляды? Вот всегда-всегда вот такой нервный смешок. Но я вас понимаю, я тоже не'},
  {'id': 1,
   'start': 6.5600000000000005,
   'end': 12.0,
   'text': ' распространяюсь о своих политических взглядах, но из-за того, что я немного медийный, обо мне иногда'},
  {'id': 2,
   'start': 12.0,
   'end': 18.68,
   'text': ' пишут, я про себя прочитал вот такое вот. Левацкое отродье. Вот так вот. И мне не понравилось, потому'},
  {'id': 3,
   'start': 18.68,
   'end': 23.52,
   'text': ' что я сам не уверен, кто я, решил загуглить, как понять, какие у тебя политические взгляды. И мне'},
  {'id': 4,
   'start': 23.52,
   'end': 27.96,
   'text': ' попалась там диаграмма политических взглядов. Вам попадалось такое? Диаграмма, по которой ты'},
  {'id': 5,
   'start': 27.96,
   'end': 35.58,
   'text': ' определяешь, кто ты. И оказалось, что я ультраправый радикал вообще. По многим взглядам совпало,'},
  {'id': 6,
   'start': 35.58,
   'end': 42.06,
   'text': ' например, отношение к гомосексуализму. У меня такое уже крайне негативное. Взять, если там'},
  {'id': 7,
   'start': 42.06,
   'end': 53.58,
   'text': ' лесбиянок, например. Я вообще не пойму, как можно хотеть женщин. Для меня это загадка. Или, например,'},
  {'id': 8,
   'start': 53.58,
   'end': 59.16,
   'text': ' отношение к эмигрантам. Я вот сам, как только, я три года назад переехал в Европу. Я как только'},
  {'id': 9,
   'start': 59.16,
   'end': 67.92,
   'text': ' переехал, я подумал, закрывайте ворота, нам эти обезьяны тут не нужны. Мы не для того, да, приехали в Европу,'},
  {'id': 10,
   'start': 67.92,
   'end': 76.86,
   'text': ' чтобы кто-то еще туда приезжал, вонял там на улицах. Для нас, европейцев, это неприемлемо уже. Ну и понятно,'},
  {'id': 11,
   'start': 76.86,
   'end': 84.0,
   'text': ' кроме меня никто европейские проблемы решать не собирается. Я решил получить паспорт Германии,'},
  {'id': 12,
   'start': 84.0,
   'end': 88.68,
   'text': ' потому что его сейчас легче всего получить. Решил получить паспорт Германии, чтобы голосовать'},
  {'id': 13,
   'start': 88.68,
   'end': 101.1,
   'text': ' исключительно за правые партии. Чтобы нашу Германию очистить от мусора. Потому что для меня,'},
  {'id': 14,
   'start': 101.1,
   'end': 112.32,
   'text': ' да, потому что для меня Германия превыше всего сейчас. Ну и естественно нужно определиться со своим'},
  {'id': 15,
   'start': 112.32,
   'end': 115.32,
   'text': ' национализмом. Пора понять, за кого я готов убивать.'}]}

## Запись после фильтрация в json файл

In [17]:
import json

with open(transcribe_path + audio_name + ".json", "w", encoding="utf-8") as f:
    json.dump(filtered_result, f, ensure_ascii=False, indent=4)

## Чтение json файла в pandas DF

In [36]:
import json
import pandas as pd

# Загрузка JSON из файла или строки
with open(
    "../data/transcripts_with_timestamp/Node quietly dropped its biggest update in years....json",
    "r",
    encoding="utf-8",
) as f:
    data = json.load(f)

# Преобразуем ключ 'segments' в DataFrame
df = pd.DataFrame(data["segments"])

# Проверка результата
df.head()

   id  start    end                                               text
0   0   0.28   3.88   Node.js just did something huge and almost no...
1   1   3.88   8.46   For the past decade, TypeScript has been repl...
2   2   8.46  10.28                                  to back-end APIs.
3   3  10.28  13.24   Everyone writes TypeScript now, whether they ...
4   4  13.24  16.40   And naturally, modern JavaScript runtimes had...

## Работа с LLM

In [9]:
import os
from google import genai
import json


# Загрузка JSON из файла или строки
with open(
    "../data/transcripts_with_timestamp/Идрак Мирзализаде. Стендап концерт Это не я придумал.json",
    "r",
    encoding="utf-8",
) as f:
    data = json.load(f)

data = data["segments"]

client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))

prompt = f"""
Вы — эксперт по тематическому анализу аудио/видео транскриптов.

На входе вы получаете список объектов вида:

[
{{'id': 0,
  'start': 0.28,
  'end': 3.88,
  'text': 'Какие у вас политические взгляды?'}},
 {{'id': 1,
  'start': 3.88,
  'end': 8.46,
  'text': 'Вот всегда, всегда вот такой нервный смешок.'}}
]

Ваша задача:
1. Проанализировать все фрагменты текста и выделить глобальные ключевые темы (например, "политические взгляды", "медиа", "самоидентификация").
2. Для каждой темы определить временной диапазон: от минимальной до максимальной отметки `timestamp`, относящейся к сообщениям этой темы.
3. Вернуть результат **строго в формате JSON**, без каких-либо комментариев, префиксов, пояснений или форматирования.

Формат ожидаемого результата:
{{
"политические взгляды": {{"start_sec": 1.564, "end_sec": 3.530}},
"медиа": {{"start_sec": 8.951, "end_sec": 9.312}},
"самоидентификация": {{"start_sec": 16.077, "end_sec": 17.647}}
}}

Вот расшифровка:
---
{data}
---
"""

response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents=prompt,
    config={
        "response_mime_type": "application/json",
    },
)

response

GenerateContentResponse(
  automatic_function_calling_history=[],
  candidates=[
    Candidate(
      content=Content(
        role='model'
      ),
      finish_reason=<FinishReason.MAX_TOKENS: 'MAX_TOKENS'>,
      index=0
    ),
  ],
  model_version='gemini-2.5-flash',
  sdk_http_response=HttpResponse(
    headers=<dict len=11>
  ),
  usage_metadata=GenerateContentResponseUsageMetadata(
    prompt_token_count=45683,
    prompt_tokens_details=[
      ModalityTokenCount(
        modality=<MediaModality.TEXT: 'TEXT'>,
        token_count=45683
      ),
    ],
    thoughts_token_count=65535,
    total_token_count=111218
  )
)

In [ ]:
formatted_text = json.loads(response.text)

formatted_text

{'Политические взгляды и Самоидентификация': {'start_sec': 0.0,
  'end_sec': 112.32},
 'Национализм и Стереотипы': {'start_sec': 112.32, 'end_sec': 264.96},
 'Расизм и Толерантность': {'start_sec': 264.96, 'end_sec': 488.68},
 'Свобода слова и Культура отмены': {'start_sec': 488.68, 'end_sec': 599.48},
 'Проблема тупости в обществе': {'start_sec': 598.48, 'end_sec': 967.48},
 'Отношения и Общественные Проблемы': {'start_sec': 967.48, 'end_sec': 1906.2},
 'Мужская анатомия и Мужские Проблемы': {'start_sec': 1908.32,
  'end_sec': 2939.32},
 'Вредные Привычки и Осознанность': {'start_sec': 2942.02, 'end_sec': 3032.8},
 'География, Жизнь за границей и Национальность': {'start_sec': 3033.26,
  'end_sec': 3105.8599999999997},
 'Такси, Стереотипы и Религия': {'start_sec': 3107.74, 'end_sec': 3152.72},
 'Комедия, Искусство и Взаимодействие с аудиторией': {'start_sec': 3160.02,
  'end_sec': 3268.12}}

# Скрапинг youtube для получения ссылок

In [ ]:
from yt_dlp import YoutubeDL

query = "стендап концерт"
search_url = f"https://www.youtube.com/results?search_query={query.replace(' ', '+')}"

ydl_opts = {
    "extract_flat": "in_playlist",
    "skip_download": True,
    "quiet": False,
    "simulate": True,
    "forceurl": True,
    "max_downloads": 10,  # ограничить число результатов
}
with YoutubeDL(ydl_opts) as ydl:
    info = ydl.extract_info(search_url, download=False)
    for entry in info.get("entries", []):
        print("https://www.youtube.com/watch?v=" + entry["id"])

https://www.youtube.com/watch?v=LV0I3_r9u-0
https://www.youtube.com/watch?v=c83NcqDvs-Y
https://www.youtube.com/watch?v=ExrG6AhR-wI
https://www.youtube.com/watch?v=M5z_OEoAOqE
https://www.youtube.com/watch?v=v1xb76zn2WQ
https://www.youtube.com/watch?v=1gAiMQkPHJc
https://www.youtube.com/watch?v=1nEDD1mQcmA
https://www.youtube.com/watch?v=di6tU8hQqSU
https://www.youtube.com/watch?v=fA-bcE6Z7eM
https://www.youtube.com/watch?v=bOzV0Okh2kw
https://www.youtube.com/watch?v=nf-s-6kppks
https://www.youtube.com/watch?v=w25BBF43seo
https://www.youtube.com/watch?v=qhx8QCDZ-cU
https://www.youtube.com/watch?v=c0ALcfrNsIQ
https://www.youtube.com/watch?v=mLGi0Si_OXU
https://www.youtube.com/watch?v=07diUFt0Weo
https://www.youtube.com/watch?v=hKu3APVhctU
https://www.youtube.com/watch?v=Xd8zyaVfp0Y
https://www.youtube.com/watch?v=td21ehWFfaM
https://www.youtube.com/watch?v=AzKFiKkJmAI
https://www.youtube.com/watch?v=X8k2WuraAoU
https://www.youtube.com/watch?v=CNGXS7O7kFg
https://www.youtube.com/watch?v=RTifScOdX-U
https://www.youtube.com/watch?v=7Ao0YfTAYz8
https://www.youtube.com/watch?v=wAy_XfHCfuA
https://www.youtube.com/watch?v=BF-zJrxOmJc
https://www.youtube.com/watch?v=hD8grH0w06o
https://www.youtube.com/watch?v=WC8MGi_sItE
https://www.youtube.com/watch?v=bq5lcy2CfTc
https://www.youtube.com/watch?v=50EE-RIUni0
https://www.youtube.com/watch?v=w4-OE-8DPUE
https://www.youtube.com/watch?v=vwPj3CWqOGI
https://www.youtube.com/watch?v=s9ynwW3it3A
https://www.youtube.com/watch?v=SDw56YBq7kI
https://www.youtube.com/watch?v=uSdqkFAiJkQ
https://www.youtube.com/watch?v=fpAc7e3S7Wg
https://www.youtube.com/watch?v=Vk8uk4ANhQM
https://www.youtube.com/watch?v=P0HMBXbTk9o
https://www.youtube.com/watch?v=63y8dH-f-UU
https://www.youtube.com/watch?v=l8HPprfq7vw
https://www.youtube.com/watch?v=eJYZrM8Y56w
https://www.youtube.com/watch?v=cZxDdgZLlLo
https://www.youtube.com/watch?v=BB6kwOzoVXo
https://www.youtube.com/watch?v=VlSLNdonYas
https://www.youtube.com/watch?v=fdx7m7tgXdQ
https://www.youtube.com/watch?v=DYB02nDkHag
https://www.youtube.com/watch?v=LidRO4oCZFI
https://www.youtube.com/watch?v=9TL3uU_BQIM
https://www.youtube.com/watch?v=hheG14PJsLs
https://www.youtube.com/watch?v=_ZAO0KCC4Ms
https://www.youtube.com/playlist?list=PLd0DZV0IlNdifgFZizt0UHwb7WbeKN6qC
https://www.youtube.com/watch?v=IfTlqfHq1d8
https://www.youtube.com/watch?v=tevCAfkGjRg
https://www.youtube.com/watch?v=nTctuRId4-4
https://www.youtube.com/watch?v=7-CR1zviAQg
https://www.youtube.com/watch?v=VjoTJ1WeWj0
https://www.youtube.com/watch?v=yZ3t-w0mGzU
https://www.youtube.com/watch?v=g3HICKj-4Zs
https://www.youtube.com/watch?v=Inc_m5aA6ik
https://www.youtube.com/watch?v=TSdoCAvQ-7I
https://www.youtube.com/watch?v=BNYj0gZBm3s
https://www.youtube.com/watch?v=mpt8q8NU0JM
https://www.youtube.com/watch?v=0JIotnt2sJY
https://www.youtube.com/shorts/3xS4hpksGkE
https://www.youtube.com/watch?v=U6CkCnJYhcU
https://www.youtube.com/watch?v=YL4ABFrVNJ8
https://www.youtube.com/watch?v=95aCRTdWGsE
https://www.youtube.com/watch?v=L3eRP0nEEW0
https://www.youtube.com/watch?v=WcZ-9LFTnuE
https://www.youtube.com/watch?v=wcNasnPDe04
https://www.youtube.com/watch?v=5bgtcArt3NU
https://www.youtube.com/watch?v=LlKOf07VTSs
https://www.youtube.com/watch?v=oyqxiFjrDKc
https://www.youtube.com/watch?v=Pfv9Xh-FHKw
https://www.youtube.com/watch?v=_sFuyM9NOs4
https://www.youtube.com/watch?v=YqA9eELfKZA
https://www.youtube.com/watch?v=hqxy6293Qlo
https://www.youtube.com/watch?v=eeBgroJMGJo
https://www.youtube.com/watch?v=t2uVHwGphR4
https://www.youtube.com/watch?v=KSw-5Rvw4dk
https://www.youtube.com/watch?v=7GAr9pJeIp0
https://www.youtube.com/watch?v=zL3VWHfSus4
https://www.youtube.com/watch?v=21JewAJdEAI
https://www.youtube.com/watch?v=VmT6chc7NtQ
https://www.youtube.com/shorts/cvjd7WqsDNI
https://www.youtube.com/watch?v=Yny4WqO0-mk
https://www.youtube.com/watch?v=cYasUYQIMYw
https://www.youtube.com/watch?v=yYDnf08zUyI
https://www.youtube.com/watch?v=_J0Tu8pgkn0
https://www.youtube.com/watch?v=mBKoIFzTV5U
https://www.youtube.com/watch?v=U_dEPJhWfQU
https://www.youtube.com/watch?v=mED6w9osqms
https://www.youtube.com/watch?v=wB8h2KZGgD8
https://www.youtube.com/watch?v=lbJXZY6rehE
https://www.youtube.com/watch?v=cktonWTy6jg
https://www.youtube.com/watch?v=WvR7K4XqDyk
https://www.youtube.com/watch?v=TzWMRIqKKD8
https://www.youtube.com/watch?v=T8GMY6k-xSk
https://www.youtube.com/watch?v=NFQ6x75xhJ8
https://www.youtube.com/watch?v=0WtdGFM1FJs
https://www.youtube.com/watch?v=tjrFqNJJJIU
https://www.youtube.com/shorts/zsRqVZyKgN8
https://www.youtube.com/watch?v=AS1QfvGamec
https://www.youtube.com/watch?v=OVPHqRzXRto
https://www.youtube.com/watch?v=ZgxSC7VlY84
https://www.youtube.com/watch?v=zc-Ihvm2hVc
https://www.youtube.com/watch?v=GCeFmj5n4NM
https://www.youtube.com/watch?v=E5kcPjkJTzA
https://www.youtube.com/watch?v=ozIwQx5zlQQ
https://www.youtube.com/watch?v=tmZxaN0avTE
https://www.youtube.com/shorts/cggRsDzAQig
https://www.youtube.com/watch?v=jjrkb65JI7I
https://www.youtube.com/watch?v=pmaCo9yvUcE
https://www.youtube.com/watch?v=Ew71mQSD1v0
https://www.youtube.com/watch?v=ZKSSwFsT8OE
https://www.youtube.com/watch?v=Eb--gykhHp4
https://www.youtube.com/watch?v=Qpvu6J_DiO0
https://www.youtube.com/watch?v=92p--kcZqa8
https://www.youtube.com/shorts/Ogdf7gQ9NmU
https://www.youtube.com/shorts/1vJrlSHxBMg
https://www.youtube.com/shorts/iBXbMSUbJlA
https://www.youtube.com/watch?v=K9qmjVlrcHw
https://www.youtube.com/watch?v=8QNaVgxlZg4
https://www.youtube.com/watch?v=GBvgQZP9EEI
https://www.youtube.com/watch?v=Ri5aBxB7kss
https://www.youtube.com/shorts/j-PGt0qDycs
https://www.youtube.com/shorts/_K2PIe_gR9M
https://www.youtube.com/watch?v=NlkaXom1kMM
https://www.youtube.com/watch?v=uehK25zWMw8
https://www.youtube.com/watch?v=zps5H5pqUiY
https://www.youtube.com/shorts/DjH0wBuCayE
https://www.youtube.com/watch?v=VYVcqWPjl1M
https://www.youtube.com/shorts/QC85u-LpOwQ
https://www.youtube.com/watch?v=hoUYA7H5ho0
https://www.youtube.com/watch?v=Eu7BZbKr3So
https://www.youtube.com/shorts/nkjKn3Pic30
https://www.youtube.com/watch?v=dDHAw7fFUZc
https://www.youtube.com/watch?v=srBFUK9qpB8
https://www.youtube.com/watch?v=nk80OSbd4OA
https://www.youtube.com/watch?v=zR1XYeX7M6Y
https://www.youtube.com/shorts/OU184jc3lFc
https://www.youtube.com/shorts/CYmUeERBrZQ
https://www.youtube.com/shorts/r0_yYClWsDE
https://www.youtube.com/watch?v=mKdCdSZ7xHk
https://www.youtube.com/watch?v=p9mQgjWFjxg
https://www.youtube.com/watch?v=YeM9RplBjfI
https://www.youtube.com/shorts/aZMyi6qW2t8
https://www.youtube.com/shorts/DTgIiJj7FpM
https://www.youtube.com/shorts/6kyK8xsGQTw
https://www.youtube.com/watch?v=srcRJX7k3cs
https://www.youtube.com/shorts/wu7tti-ktnw
https://www.youtube.com/watch?v=f0526oXVn88
https://www.youtube.com/watch?v=fJ_OOhlVmGs
https://www.youtube.com/watch?v=_dgnzJcP7JU
https://www.youtube.com/watch?v=idUkymOQYJs
https://www.youtube.com/shorts/9fXbW_dQrgc
https://www.youtube.com/watch?v=wjuvaaxccAQ
https://www.youtube.com/watch?v=CF-pHTtYKF8
https://www.youtube.com/watch?v=BsQXtMRD-uI
https://www.youtube.com/watch?v=vAburjD-2tY
https://www.youtube.com/watch?v=iOx3PXVKP-o
https://www.youtube.com/watch?v=kD5jbuc9HhA
https://www.youtube.com/watch?v=KSZZQBFUfGc
https://www.youtube.com/watch?v=Bv2K5BDnbBk
https://www.youtube.com/watch?v=SBkqYnepaY4
https://www.youtube.com/watch?v=WSPSb2Zug34
https://www.youtube.com/watch?v=LYHrO0TaH40
https://www.youtube.com/watch?v=k8Mixx5Q4vc
https://www.youtube.com/shorts/iSWLjYpU6mE
https://www.youtube.com/watch?v=EwjHqvAcLzA
https://www.youtube.com/watch?v=zlQH7OAnE5I
https://www.youtube.com/watch?v=VjS7ffUuEIk
https://www.youtube.com/shorts/9G-XOpqpXz4
https://www.youtube.com/watch?v=i3OTskskU1M
https://www.youtube.com/shorts/HNbgHSQghXI
https://www.youtube.com/shorts/EVAZwyygRQQ
https://www.youtube.com/shorts/gwVVxFsciZg
https://www.youtube.com/watch?v=3FeLwENk-5w
https://www.youtube.com/shorts/dg1qv2bn7tU
https://www.youtube.com/watch?v=1jmlzqOKMx4
https://www.youtube.com/shorts/HXWN0QasfvQ
https://www.youtube.com/shorts/Q1qS7TVojIo
https://www.youtube.com/shorts/m7sibssQieQ
https://www.youtube.com/watch?v=hI_IjTs8pwE
https://www.youtube.com/shorts/hQ4xvxeRACg
https://www.youtube.com/shorts/y5THdVn4bdg
https://www.youtube.com/shorts/Pur9XJwJVP0
https://www.youtube.com/watch?v=OK_VFmaySTk
https://www.youtube.com/watch?v=x_KiTM_xJwc
https://www.youtube.com/watch?v=Mr5AwlHxiUI
https://www.youtube.com/watch?v=QzDBz2cIXOU
https://www.youtube.com/watch?v=1tQNJgRDwyw
https://www.youtube.com/shorts/JzkGmAuNiaE
https://www.youtube.com/shorts/2zjFbG0DIRw
https://www.youtube.com/watch?v=L0x9ett6RO8
https://www.youtube.com/shorts/a4IR6E9aQWM
https://www.youtube.com/watch?v=UoZD8jg8qqk
https://www.youtube.com/shorts/qMf4RuvIoZ4
https://www.youtube.com/watch?v=Hv8TcZgwNcI
https://www.youtube.com/shorts/_6S4DRkfuF8
https://www.youtube.com/watch?v=j6VDZl2ByD8
https://www.youtube.com/watch?v=myTl_gxJ0xA
https://www.youtube.com/watch?v=EgLH0bv0SVA
https://www.youtube.com/watch?v=ObanPxs-G1o
https://www.youtube.com/watch?v=ztLyKVA5-OI
https://www.youtube.com/shorts/whGCVkPGU0Q
https://www.youtube.com/watch?v=VTsYcXtqhzo
https://www.youtube.com/shorts/B8dNJ6ayco0
https://www.youtube.com/watch?v=FXkdlMXokcA
https://www.youtube.com/watch?v=1u6YZWAKt6E
https://www.youtube.com/watch?v=2mmyR1r0z2k
https://www.youtube.com/shorts/InJXY99RyWQ
https://www.youtube.com/watch?v=v5E4LobrQ2E
https://www.youtube.com/watch?v=HEZMO8rX24Q
https://www.youtube.com/watch?v=5h7zwKRWd_w
https://www.youtube.com/shorts/IMCamtQBmf0
https://www.youtube.com/shorts/KmMnpA9TudI
https://www.youtube.com/watch?v=g27RecZJvRQ
https://www.youtube.com/watch?v=7mimIaPcLZM
https://www.youtube.com/playlist?list=PLd0DZV0IlNdifgFZizt0UHwb7WbeKN6qC
https://www.youtube.com/playlist?list=PLd0DZV0IlNdifgFZizt0UHwb7WbeKN6qC
https://www.youtube.com/watch?v=sQXYuJfbecs
https://www.youtube.com/watch?v=lbxwegfhGOg
https://www.youtube.com/watch?v=n3S1PTtOo3M
https://www.youtube.com/watch?v=azJqeLcoB8o
https://www.youtube.com/watch?v=t2_SQkHVau4
https://www.youtube.com/watch?v=Rdd7hUP0uNY
https://www.youtube.com/shorts/PGcV_Kwk1JU
https://www.youtube.com/shorts/EIglJ6VrJz0
https://www.youtube.com/shorts/39Lp46WoczY
https://www.youtube.com/watch?v=WYZ1FiHMH6M
https://www.youtube.com/shorts/3TvC7KIPPbs
https://www.youtube.com/shorts/3ElSFXp8R6k
https://www.youtube.com/watch?v=NAx-GW1OE0o
https://www.youtube.com/watch?v=_3BOxJdFcXk
https://www.youtube.com/watch?v=YGZOwbIsvgY
https://www.youtube.com/watch?v=KEhiWYqaDUU
https://www.youtube.com/watch?v=bk6i4IQ3b54
https://www.youtube.com/shorts/qB4EMyu70Zc
https://www.youtube.com/watch?v=DiOoyOJaNno
https://www.youtube.com/watch?v=MMKeEUXjO8Y
https://www.youtube.com/watch?v=QBvW8qFbYqk
https://www.youtube.com/shorts/Hvsv_e2JWQY
https://www.youtube.com/watch?v=7mimIaPcLZM
https://www.youtube.com/watch?v=rrNk-LEQ2P0
https://www.youtube.com/shorts/cpXa7qTFdAc
https://www.youtube.com/watch?v=PW2riGJkjX4
https://www.youtube.com/watch?v=dSmaRhRfXic
https://www.youtube.com/watch?v=j2mVh6lPApE
https://www.youtube.com/watch?v=Hv5jy29wJ9Q
https://www.youtube.com/shorts/0LGC4Rm2A5w
https://www.youtube.com/watch?v=3NY9zohr538
https://www.youtube.com/shorts/j91urCCewYw
https://www.youtube.com/shorts/-ayvCO2xJfc
https://www.youtube.com/shorts/m7A_-vhPTIU
https://www.youtube.com/shorts/LQ43u11yg_o
https://www.youtube.com/shorts/L5NPYBy-pJ4
https://www.youtube.com/watch?v=__adxwQIlZ0
https://www.youtube.com/watch?v=0SCtrOLCsvs
https://www.youtube.com/watch?v=mbpzXYOVE4I
https://www.youtube.com/shorts/Lx6q99gSrco
https://www.youtube.com/shorts/hV8bQnzjtP0
https://www.youtube.com/shorts/cMAZAWLAKM0
https://www.youtube.com/shorts/5zT5rD_gj6Y
https://www.youtube.com/shorts/yYdqp4tVPH8
https://www.youtube.com/watch?v=rc-hqNDHApA
https://www.youtube.com/watch?v=e7edgd1WJDg
https://www.youtube.com/shorts/x3sV50Srua8
https://www.youtube.com/shorts/QpNUG44e3WY
https://www.youtube.com/shorts/Rs035PxWzKI
https://www.youtube.com/shorts/GRq6NBizGSo
https://www.youtube.com/watch?v=3gyZM2d9hKk
https://www.youtube.com/watch?v=U02D0b31wLM
https://www.youtube.com/watch?v=zktq5G8dopY
https://www.youtube.com/shorts/0vDNdDyA9NM
https://www.youtube.com/shorts/dCFzEtN8iok
https://www.youtube.com/shorts/HC9Zpn47Iu4
https://www.youtube.com/shorts/tvKyO13nfLM
https://www.youtube.com/shorts/da1cG6PIXHE
https://www.youtube.com/watch?v=DF1rV5t9vGI
https://www.youtube.com/shorts/1F7DFDLTLak
https://www.youtube.com/watch?v=USHMRp5qkyA
https://www.youtube.com/shorts/YFPgwJ3MaaM
https://www.youtube.com/shorts/GiJp3Wqjwh0
https://www.youtube.com/shorts/s1QZy-Ks6uY
https://www.youtube.com/watch?v=21jzaBsfcCM
https://www.youtube.com/shorts/tu_rxX_s-ig
https://www.youtube.com/shorts/xeA-xVkyzoQ
https://www.youtube.com/shorts/X9qcAhL3RU8
https://www.youtube.com/shorts/ddfC7axS1Ek
https://www.youtube.com/shorts/k3raSdrI0m8
https://www.youtube.com/shorts/jMv49DOiqSg
https://www.youtube.com/shorts/eufAf2Iq6vU
https://www.youtube.com/shorts/W8JYFbEsI2s
https://www.youtube.com/watch?v=7H8JH4R4-8w
https://www.youtube.com/shorts/JxBTHfalYgE
https://www.youtube.com/shorts/XsDmutIlY8k
https://www.youtube.com/shorts/r8Pv1gjwzPk
https://www.youtube.com/shorts/X6iU9cchM4Y
https://www.youtube.com/shorts/iDrnR9hD6so
https://www.youtube.com/shorts/bCJCNG6CPTU
https://www.youtube.com/shorts/KSA-V-TtUHI
https://www.youtube.com/watch?v=N9f1VudSSp8
https://www.youtube.com/shorts/sM0iLBgpLN0
https://www.youtube.com/shorts/5E9Kg226aKk
https://www.youtube.com/shorts/FyVlQUeeaDA
https://www.youtube.com/shorts/Pv151rWKQEs
https://www.youtube.com/shorts/tiuyu5Ocbj8
https://www.youtube.com/watch?v=Uzib6HJiMM4
https://www.youtube.com/shorts/3MPQlKgOUJU
https://www.youtube.com/watch?v=7JTzu6Pv0Ms
https://www.youtube.com/shorts/QSmAqEf0dWA
https://www.youtube.com/shorts/I3hwagHfZg4
https://www.youtube.com/shorts/SpyNKY9cWvE
https://www.youtube.com/watch?v=vBcNVrhWKM8
https://www.youtube.com/shorts/RG_92WKS808
https://www.youtube.com/watch?v=82emOwRr8Wo
https://www.youtube.com/shorts/Ce5Ua2tEa-0
https://www.youtube.com/shorts/d_JuVXvILdI
https://www.youtube.com/watch?v=ag97HF1lYNI
https://www.youtube.com/watch?v=MGR-EgkyHXM
https://www.youtube.com/shorts/V0GnN4hvOek
https://www.youtube.com/shorts/DVBO18s52Gk
https://www.youtube.com/shorts/1A7FK4a4t7Q
https://www.youtube.com/shorts/6CV2VYIYCG0
https://www.youtube.com/watch?v=Vv2CQhiswMI
https://www.youtube.com/shorts/ZiUIvgCAoVA
https://www.youtube.com/shorts/zgEQmGQgyGM
https://www.youtube.com/shorts/mnR1zqm7w58
https://www.youtube.com/shorts/YYr6I1u7tVA
https://www.youtube.com/shorts/rd6UM2Y30dc
https://www.youtube.com/watch?v=EHv7puQht_o
https://www.youtube.com/shorts/Aa0orEirkO0
https://www.youtube.com/shorts/SfntGlg0iHU
https://www.youtube.com/shorts/SJ7jfikj9Ms
https://www.youtube.com/watch?v=--wzQCWi7p8
https://www.youtube.com/shorts/4HKOnqa57wg
https://www.youtube.com/watch?v=EzHJH5JKu_4
https://www.youtube.com/shorts/lspB90z94MY
https://www.youtube.com/shorts/rOjr-WQmInk
https://www.youtube.com/shorts/oURJI5dE5SI
https://www.youtube.com/shorts/26sHCaSMx9I
https://www.youtube.com/shorts/bkVWI_61zaQ
https://www.youtube.com/shorts/NT3ANjUvhb4
https://www.youtube.com/shorts/3etTHTT54C8
https://www.youtube.com/shorts/qTzdvtqUncA
https://www.youtube.com/watch?v=7gOY-pu0iIY
https://www.youtube.com/shorts/S2oeBqmXtr4
https://www.youtube.com/watch?v=SwdyJp4e2bs
https://www.youtube.com/shorts/P-0065Sc7ac
https://www.youtube.com/watch?v=z0jj893SrkM
https://www.youtube.com/shorts/mPTywIq5Ke8
https://www.youtube.com/shorts/E0qm1qwRwxU
https://www.youtube.com/shorts/7aTDwP7Elkw
https://www.youtube.com/shorts/zQHrOxqYIaY
https://www.youtube.com/watch?v=FQVphmR2-R4
https://www.youtube.com/shorts/f6ZO3azCJ9c
https://www.youtube.com/shorts/ZllgxFvmif0
https://www.youtube.com/shorts/GxsgbaJ5l8g
https://www.youtube.com/watch?v=_Ms5EHr19Ks
https://www.youtube.com/shorts/VtWdeX_4Huw
https://www.youtube.com/watch?v=HqtbqPRFnKU
https://www.youtube.com/shorts/P7725_oz3Ps
https://www.youtube.com/shorts/04S4HsG7MhM
https://www.youtube.com/watch?v=suCNho5MdL8
https://www.youtube.com/shorts/BDE64GZsbo0
https://www.youtube.com/watch?v=vX7XFqgdi4g
https://www.youtube.com/shorts/sQMCMPnZBoA
https://www.youtube.com/shorts/_yIItyI0QUc
https://www.youtube.com/shorts/DgQb8OIwo2g
https://www.youtube.com/shorts/0-G2QJSprBg
https://www.youtube.com/shorts/K-cyTrX8dQ0
https://www.youtube.com/shorts/NOpWDSLg2DE
https://www.youtube.com/shorts/-lfLn-9hB94
https://www.youtube.com/shorts/fXhPuc0hbls
https://www.youtube.com/watch?v=YqfaeSjy_uA
https://www.youtube.com/shorts/5lwaddezdT0
https://www.youtube.com/shorts/Rn3cNWBvoNQ
https://www.youtube.com/shorts/iFDTVHb2tC4
https://www.youtube.com/shorts/4KC3A4W3t6Y
https://www.youtube.com/shorts/QdQrA4dXK-0
https://www.youtube.com/watch?v=PvvP5JnuV1o
https://www.youtube.com/shorts/YYjNWTPYLno
https://www.youtube.com/shorts/vmvI7GGgHp8
https://www.youtube.com/shorts/2GpVDTlUXtk
https://www.youtube.com/shorts/bE2IsrVGRO0
https://www.youtube.com/shorts/c8Uu7D8HSsg
https://www.youtube.com/watch?v=DcwucGrXQYg
https://www.youtube.com/shorts/o73MMMiTCYE
https://www.youtube.com/shorts/G9DF5aRpA4E
https://www.youtube.com/shorts/7m1oc6kzTSI
https://www.youtube.com/watch?v=TxHGTqfji6E
https://www.youtube.com/shorts/2dN0XbIdI4A
https://www.youtube.com/shorts/7nrchGrv1_0
https://www.youtube.com/shorts/hKSDem0p91M
https://www.youtube.com/watch?v=4140kXTRnzQ
https://www.youtube.com/shorts/YavfLDGrx9w
https://www.youtube.com/shorts/YjKtcDPg8hs
https://www.youtube.com/watch?v=WWRlgSmvMHM
https://www.youtube.com/shorts/11wN6rA6WSY
https://www.youtube.com/shorts/fMdZfZA9O1U
https://www.youtube.com/shorts/bYZXqcEXusc
https://www.youtube.com/watch?v=6-ZeXR9Ep08
https://www.youtube.com/shorts/1iWtRAEHr9Y
https://www.youtube.com/shorts/7Q48QjroGAU
https://www.youtube.com/shorts/3ULZdSDtS4U
https://www.youtube.com/watch?v=exX4mw3FKdQ
https://www.youtube.com/shorts/XKMeVfaeSLU
https://www.youtube.com/shorts/Da3W3eqz_Jg
https://www.youtube.com/shorts/PaOBoieNMQM
https://www.youtube.com/shorts/N9NNwGdljy8
https://www.youtube.com/shorts/PWGEG4aYWHc
https://www.youtube.com/shorts/0UordzkEYqo
https://www.youtube.com/watch?v=pQm531crALg
https://www.youtube.com/shorts/Wh6O0O4IblQ
https://www.youtube.com/shorts/Ntd52X8JcBs
https://www.youtube.com/shorts/jm2OzPz-n2I
https://www.youtube.com/shorts/3vLcxjDHDbA
https://www.youtube.com/shorts/xjC_vvSKcQo
https://www.youtube.com/shorts/xw-xoKZDOqE
https://www.youtube.com/watch?v=3mwVIHKtnUY
https://www.youtube.com/shorts/Xs2JUHRFdZA
https://www.youtube.com/shorts/drHLZDLVZD8
https://www.youtube.com/shorts/X4rgUbxyrUM
https://www.youtube.com/shorts/V9nZQHu68_c
https://www.youtube.com/shorts/KjsP7ILBpvQ
https://www.youtube.com/shorts/16Lt0GQqSQw
https://www.youtube.com/shorts/3tLCLILwz2s
https://www.youtube.com/shorts/935T-lWI0gs
https://www.youtube.com/shorts/n3mbojui3Mk
https://www.youtube.com/shorts/Xv4u6vpfa8k
https://www.youtube.com/watch?v=XBqArmne6w8
https://www.youtube.com/watch?v=xRG-ZgZ-HDE
https://www.youtube.com/shorts/L5m6vT48qb8
https://www.youtube.com/shorts/rQGWvQa77a8
https://www.youtube.com/shorts/Si68FlvslVg
https://www.youtube.com/shorts/POCwHlGYX0A
https://www.youtube.com/shorts/VYmDmMFEriI
https://www.youtube.com/shorts/EwAW0mm9784
https://www.youtube.com/shorts/hiT9QQsnx6o
https://www.youtube.com/watch?v=OPsqf3zz26c
https://www.youtube.com/shorts/Lwr-BD2QgsA
https://www.youtube.com/watch?v=YDg4zeBjSFY
https://www.youtube.com/shorts/ji5MRWwl97g
https://www.youtube.com/shorts/Yb57Mj5S4DM
https://www.youtube.com/shorts/cj8E24xnb6g
https://www.youtube.com/shorts/DsS_b0VHyXQ
https://www.youtube.com/shorts/9oTr2BmPa5o
https://www.youtube.com/shorts/SPataH3UZ1o
https://www.youtube.com/watch?v=7xKAFQJfyPY
https://www.youtube.com/shorts/JWB5Uuwi0as
https://www.youtube.com/shorts/gcH3T07_lIs
https://www.youtube.com/watch?v=v4_zGQtZ3u0
https://www.youtube.com/watch?v=Vy4CEl-a68U
https://www.youtube.com/shorts/F1_zImSv9gY
https://www.youtube.com/shorts/hOTprNZXXig
https://www.youtube.com/watch?v=1E-6BxVuTv0

In [8]:
import yt_dlp

URLS = "https://www.youtube.com/watch?v=LV0I3_r9u-0&t=503s"


class MyLogger:
    def debug(self, msg):
        # For compatibility with youtube-dl, both debug and info are passed into debug
        # You can distinguish them by the prefix '[debug] '
        if msg.startswith("[debug] "):
            pass
        else:
            self.info(msg)

    def info(self, msg):
        pass

    def warning(self, msg):
        pass

    def error(self, msg):
        print(msg)


# ℹ️ See "progress_hooks" in help(yt_dlp.YoutubeDL)
def my_hook(d):
    if d["status"] == "finished":
        print("Done downloading, now post-processing ...")


ydl_opts = {
    "logger": MyLogger(),
    "progress_hooks": [my_hook],
}

with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    ydl.download(URLS)

Done downloading, now post-processing ...
Done downloading, now post-processing ...

# Скачивание датасетов с HF

In [11]:
import pandas as pd
from datasets import load_dataset

dataset = load_dataset("RayYuki/CodecBench_laughterscape_ver1.0", split="train")

# В DataFrame
df = pd.DataFrame(dataset)
df

,filename,audio,sample_rate,duration
0,spkr063-utt013.wav,"{'path': 'spkr063-utt013.wav', 'array': [0.001...",24000,0.510042
1,spkr377-utt003.wav,"{'path': 'spkr377-utt003.wav', 'array': [-0.00...",24000,1.220042
2,spkr223-utt006.wav,"{'path': 'spkr223-utt006.wav', 'array': [-0.00...",24000,2.110042
3,spkr371-utt005.wav,"{'path': 'spkr371-utt005.wav', 'array': [-0.00...",24000,0.900042
4,spkr272-utt050.wav,"{'path': 'spkr272-utt050.wav', 'array': [0.000...",24000,0.922042
...,...,...,...,...
8165,spkr148-utt004.wav,"{'path': 'spkr148-utt004.wav', 'array': [0.001...",24000,1.420000
8166,spkr356-utt007.wav,"{'path': 'spkr356-utt007.wav', 'array': [-0.00...",24000,0.586042
8167,spkr085-utt180.wav,"{'path': 'spkr085-utt180.wav', 'array': [-0.01...",24000,0.639042
8168,spkr212-utt020.wav,"{'path': 'spkr212-utt020.wav', 'array': [-3.05...",24000,2.615042
8169,spkr085-utt008.wav,"{'path': 'spkr085-utt008.wav', 'array': [-0.00...",24000,0.408042

# SWIFT test

Требуется редактирование swift кода и последующая компеляция командой:
swiftc main.swift -o SoundFileClassifier

## Усович

In [ ]:
# # Тест нормализации звука

# from pydub import AudioSegment, effects

# # Загружаем аудио
# audio = AudioSegment.from_wav(
#     "/Users/aleksandr/Documents/Projects/StandUP_project/data/audio/Ваня Усович ＂ЕЩЕ ОДИН ДЕНЬ＂ 2020.wav"
# )

# # 1. Выравнивание уровня громкости (RMS normalization)
# normalized_audio = effects.normalize(audio)

# # 2. Применение компрессии для уменьшения разницы между громкой речью и тихим смехом
# compressed_audio = normalized_audio.compress_dynamic_range()

# # Сохранение
# compressed_audio.export(
#     "/Users/aleksandr/Documents/Projects/StandUP_project/data/audio/Ваня Усович ＂ЕЩЕ ОДИН ДЕНЬ＂ 2020_normalized_output.wav",
#     format="wav",
# )

In [ ]:
# Список аргументов для передачи swift приложению
# Usage: SoundFileClassifier <input_audio_path.wav> <output_json_path.json> <window_duration_seconds> <preferred_timescale> <confidence_threshold>

import subprocess

audio_path = "/Users/aleksandr/Documents/Projects/StandUP_project/data/audio/Ваня Усович ＂ЕЩЕ ОДИН ДЕНЬ＂ 2020_normalized_output.wav"
output_path = "/Users/aleksandr/Documents/Projects/StandUP_project/data/laughter_segmentation_json/Ivan_normalized_output.json"
window_duration_seconds = "0.5"  # min - 0.5
preferred_timescale = "1000"  # дробная часть секунды 1 / preferred_timescale
confidence_threshold = "0.25"  # определение нижней границы чувствительности смеха

subprocess.run(
    [
        "/Users/aleksandr/Documents/Projects/StandUP_project/src/SoundFileClassifier",  # путь до swift бинарника
        audio_path,
        output_path,
        window_duration_seconds,
        preferred_timescale,
        confidence_threshold,
    ]
)

The request completed successfully!
Результаты анализа сохранены в: /Users/aleksandr/Documents/Projects/StandUP_project/data/laughter_segmentation_json/Ivan_normalized_output.json

CompletedProcess(args=['/Users/aleksandr/Documents/Projects/StandUP_project/src/SoundFileClassifier', '/Users/aleksandr/Documents/Projects/StandUP_project/data/audio/Ваня Усович ＂ЕЩЕ ОДИН ДЕНЬ＂ 2020_normalized_output.wav', '/Users/aleksandr/Documents/Projects/StandUP_project/data/laughter_segmentation_json/Ivan_normalized_output.json', '0.5', '1000', '0.25'], returncode=0)

In [12]:
import json
import pandas as pd

# Загрузка JSON из файла
with open("../data/laughter_segmentation_json/Ivan_normalized_output.json", "r") as f:
    data = json.load(f)

# Преобразование в DataFrame
df_ivan = pd.DataFrame(list(data.items()), columns=["time", "confidence"])

# Преобразование time в float (если требуется числовая ось)
df_ivan["time"] = df_ivan["time"].astype(float)

# Сортировка по времени (опционально)
df_ivan.sort_values("time", inplace=True)

# Результат
df_ivan

         time  confidence
245      2.75    0.282760
638      4.25    0.268598
724      5.75    0.303010
1059     6.25    0.322871
1354     6.75    0.272182
...       ...         ...
31    3242.00    0.279420
1643  3243.00    0.259268
900   3243.25    0.311682
982   3244.50    0.253812
1573  3254.50    0.294648

[1736 rows x 2 columns]

## Идрак

In [ ]:
# Usage: SoundFileClassifier <input_audio_path.wav> <output_json_path.json> <window_duration_seconds> <preferred_timescale> <confidence_threshold>

import subprocess

audio_path = "/Users/aleksandr/Documents/Projects/StandUP_project/data/audio/Идрак Мирзализаде. Стендап концерт Это не я придумал.wav"
output_path = "/Users/aleksandr/Documents/Projects/StandUP_project/data/laughter_segmentation_json/Idrak.json"
window_duration_seconds = "0.5"  # min - 0.5
preferred_timescale = "1000"  # дробная часть секунды 1 / preferred_timescale
confidence_threshold = "0.25"  # определение нижней границы чувствительности смеха

subprocess.run(
    [
        "/Users/aleksandr/Documents/Projects/StandUP_project/src/SoundFileClassifier",  # путь до бинарника
        audio_path,
        output_path,
        window_duration_seconds,
        preferred_timescale,
        confidence_threshold,
    ]
)

The request completed successfully!
Результаты анализа сохранены в: /Users/aleksandr/Documents/Projects/StandUP_project/data/laughter_segmentation_json/Idrak.json

CompletedProcess(args=['/Users/aleksandr/Documents/Projects/StandUP_project/src/SoundFileClassifier', '/Users/aleksandr/Documents/Projects/StandUP_project/data/audio/Идрак Мирзализаде. Стендап концерт Это не я придумал.wav', '/Users/aleksandr/Documents/Projects/StandUP_project/data/laughter_segmentation_json/Idrak.json', '1', '1000', '0.3'], returncode=0)

In [21]:
import json
import pandas as pd

# Загрузка JSON из файла
with open("../data/laughter_segmentation_json/Idrak.json", "r") as f:
    data = json.load(f)

# Преобразование в DataFrame
df_idrak = pd.DataFrame(list(data.items()), columns=["time", "confidence"])

# Преобразование time в float (если требуется числовая ось)
df_idrak["time"] = df_idrak["time"].astype(float)

# Сортировка по времени (опционально)
df_idrak.sort_values("time", inplace=True)

# Результат
df_idrak

        time  confidence
1488     1.5    0.547360
2023     2.5    0.622392
1267     3.0    0.805686
1539     8.5    0.512357
2011    16.0    0.761802
...      ...         ...
413   3260.5    0.779873
2399  3261.0    0.580877
24    3261.5    0.615865
2422  3262.0    0.447715
637   3262.5    0.606343

[2525 rows x 2 columns]

## Дима

In [ ]:
# Usage: SoundFileClassifier <input_audio_path.wav> <output_json_path.json> <window_duration_seconds> <preferred_timescale> <confidence_threshold>

import subprocess

audio_path = "/Users/aleksandr/Documents/Projects/StandUP_project/data/audio/Дима Коваль. Стендап концерт из Вегаса..wav"
output_path = "/Users/aleksandr/Documents/Projects/StandUP_project/data/laughter_segmentation_json/Dima.json"
window_duration_seconds = "0.5"  # min - 0.5
preferred_timescale = "1000"  # дробная часть секунды 1 / preferred_timescale
confidence_threshold = "0.25"  # определение нижней границы чувствительности смеха

subprocess.run(
    [
        "/Users/aleksandr/Documents/Projects/StandUP_project/src/SoundFileClassifier",  # путь до бинарника
        audio_path,
        output_path,
        window_duration_seconds,
        preferred_timescale,
        confidence_threshold,
    ]
)

The request completed successfully!
Результаты анализа сохранены в: /Users/aleksandr/Documents/Projects/StandUP_project/data/laughter_segmentation_json/Dima.json

CompletedProcess(args=['/Users/aleksandr/Documents/Projects/StandUP_project/src/SoundFileClassifier', '/Users/aleksandr/Documents/Projects/StandUP_project/data/audio/Дима Коваль. Стендап концерт из Вегаса..wav', '/Users/aleksandr/Documents/Projects/StandUP_project/data/laughter_segmentation_json/Dima.json', '1', '1000', '0.3'], returncode=0)

In [23]:
import json
import pandas as pd

# Загрузка JSON из файла
with open("../data/laughter_segmentation_json/Dima.json", "r") as f:
    data = json.load(f)

# Преобразование в DataFrame
df_idrak = pd.DataFrame(list(data.items()), columns=["time", "confidence"])

# Преобразование time в float (если требуется числовая ось)
df_idrak["time"] = df_idrak["time"].astype(float)

# Сортировка по времени (опционально)
df_idrak.sort_values("time", inplace=True)

# Результат
df_idrak

       time  confidence
386    28.5    0.418664
104    29.0    0.523689
110    29.5    0.316232
22     31.0    0.347578
146    43.0    0.552869
..      ...         ...
268  1058.0    0.366513
195  1064.0    0.909561
465  1064.5    0.824979
500  1065.0    0.707863
318  1065.5    0.522286

[506 rows x 2 columns]